if(typeof dartCallbackObjects=="undefined")var dartCallbackObjects=new Array;if(typeof dartCreativeDisplayManagers=="undefined")var dartCreativeDisplayManagers=new Object;if(typeof dartMotifAds=="undefined")var dartMotifAds=new Array;if(!self.dartLoadedGlobalTemplates_69_11)self.dartLoadedGlobalTemplates_69_11={};if(self.dartLoadedGlobalTemplates_69_11["floatingIframe"])self.dartLoadedGlobalTemplates_69_11["floatingIframe"].isLoaded=true;
function RichMediaCore_69_11(){this.CREATIVE_TYPE_EXPANDING="ExpandingFlash";this.CREATIVE_TYPE_FLOATING="FloatingFlash";this.CREATIVE_TYPE_INPAGE="InpageFlash";this.CREATIVE_TYPE_MULTI_FLOATING="MultiFloatingFlash";this.CREATIVE_TYPE_INPAGE_WITH_FLOATING="InpageFlashFloatingFlash";this.CREATIVE_TYPE_FLOATING_WITH_REMINDER="FloatingFlashReminderFlash";this.CREATIVE_TYPE_INPAGE_WITH_OVERLAY="InpageFlashOverlayFlash";this.ASSET_TYPE_FLOATING="Floating";this.ASSET_TYPE_INPAGE="Inpage";this.ASSET_TYPE_EXPANDING=
"Expanding";this.ASSET_TYPE_REMINDER="Reminder";this.ASSET_TYPE_OVERLAY="Overlay";this.STANDARD_EVENT_DISPLAY_TIMER="DISPLAY_TIMER";this.STANDARD_EVENT_INTERACTION_TIMER="INTERACTION_TIMER";this.STANDARD_EVENT_INTERACTIVE_IMPRESSION="EVENT_USER_INTERACTION";this.STANDARD_EVENT_FULL_SCREEN_VIDEO_PLAYS="";this.STANDARD_EVENT_FULL_SCREEN_VIDEO_COMPLETES="";this.STANDARD_EVENT_FULL_SCREEN_AVERAGE_VIEW_TIME="";this.STANDARD_EVENT_MANUAL_CLOSE="EVENT_MANUAL_CLOSE";this.STANDARD_EVENT_BACKUP_IMAGE="BACKUP_IMAGE_IMPRESSION";
this.STANDARD_EVENT_EXPAND_TIMER="EXPAND_TIMER";this.STANDARD_EVENT_VIDEO_PLAY="EVENT_VIDEO_PLAY";this.STANDARD_EVENT_VIDEO_VIEW_TIMER="EVENT_VIDEO_VIEW_TIMER";this.STANDARD_EVENT_VIDEO_VIEW_COMPLETE="EVENT_VIDEO_COMPLETE";this.STANDARD_EVENT_VIDEO_INTERACTION="EVENT_VIDEO_INTERACTION";this.STANDARD_EVENT_VIDEO_PAUSE="EVENT_VIDEO_PAUSE";this.STANDARD_EVENT_VIDEO_MUTE="EVENT_VIDEO_MUTE";this.STANDARD_EVENT_VIDEO_REPLAY="EVENT_VIDEO_REPLAY";this.STANDARD_EVENT_VIDEO_MIDPOINT="EVENT_VIDEO_MIDPOINT";
this.STANDARD_EVENT_VIDEO_FULLSCREEN="";this.STANDARD_EVENT_VIDEO_STOP="EVENT_VIDEO_STOP";this.STANDARD_EVENT_VIDEO_UNMUTE="EVENT_VIDEO_UNMUTE";this.STANDARD_EVENT_FULLSCREEN="EVENT_FULLSCREEN";this.STANDARD_EVENT_DYNAMIC_CREATIVE_IMPRESSION="DYNAMIC_CREATIVE_IMPRESSION";this.STANDARD_EVENT_HTML5_CREATIVE_IMPRESSION="HTML5_CREATIVE_IMPRESSION"}RichMediaCore_69_11.prototype.isPageLoaded=false;RichMediaCore_69_11.prototype.csiTimes=new Object;
RichMediaCore_69_11.prototype.setCsiEventsRecordedDuringBreakout=function(a){if(a.gtStartLoadingTime!=undefined)this.csiTimes["gb"]=a.gtStartLoadingTime};RichMediaCore_69_11.prototype.csiHasValidStart=function(a){return a.csiAdRespTime>=0&&a.csiAdRespTime<100000};RichMediaCore_69_11.prototype.shouldReportCsi=function(a){return this.csiHasValidStart(a)||Math.floor(Math.random()*1001)==1};
RichMediaCore_69_11.prototype.shouldCsi=function(a,b){switch(b){case this.CREATIVE_TYPE_INPAGE_WITH_FLOATING:return a.assetType==this.ASSET_TYPE_INPAGE;case this.CREATIVE_TYPE_FLOATING_WITH_REMINDER:return a.assetType==this.ASSET_TYPE_FLOATING;case this.CREATIVE_TYPE_INPAGE_WITH_OVERLAY:return a.assetType==this.ASSET_TYPE_INPAGE;default:return true}};RichMediaCore_69_11.prototype.trackCsiEvent=function(a){this.csiTimes[a]=(new Date).getTime()};
RichMediaCore_69_11.prototype.getCsiServer=function(){return self.location.protocol&&self.location.protocol.toString().toLowerCase()=="https:"?"https://static.doubleclick.net":"http://static.2mdn.net"};
RichMediaCore_69_11.prototype.reportCsi=function(a){if(!a.previewMode&&this.shouldReportCsi(a)){var b=this.getCsiServer()+"/csi/d?s=rmad&v=2&rt=";var c="";var d="";for(var e in this.csiTimes){var f=this.csiTimes[e]-a.csiBaseline;b+=e+"."+(f>0?f:0)+",";if(e=="pb"||e=="gb"||e=="fb")c+=e+"."+(f>0?f:0)+","}b=b.replace(/\,$/,"");var g=this.csiTimes["pe"]-this.csiTimes["pb"];var h=this.csiTimes["ge"]-this.csiTimes["gb"];var i=this.csiTimes["fe"]-this.csiTimes["fb"];d="pl."+(g>0?g:0)+","+"gl."+(h>0?h:0)+
","+"fl."+(i>0?i:0);b+="&irt="+c.replace(/\,$/,"")+"&it="+d;var j=new RegExp(/(.*\/\/)/);b+="&adi=asd_"+a.adServer.replace(j,"")+",csd_"+a.mediaServer.replace(j,"")+",gt_"+a.globalTemplateJs.replace(/(.*\/)/,"");if(this.csiHasValidStart(a))b+="&srt="+a.csiAdRespTime;this.trackUrl(b,true,a.previewMode)}};RichMediaCore_69_11.prototype._isValidStartTime=function(a){return this._isValidNumber(a)};
RichMediaCore_69_11.prototype._convertDuration=function(a){if(a){a=a.toString().toUpperCase();switch(a){case "AUTO":return"AUTO";case "NONE":return 0;default:return this._isValidNumber(a)?eval(a):0}}return 0};RichMediaCore_69_11.prototype.convertUnit=function(a){if(a!=""){a=a.toLowerCase().replace(new RegExp("pct","g"),"%");if(a.indexOf("%")<0&&a.indexOf("px")<0&&a.indexOf("pxc")<0)a+="px"}return a};
RichMediaCore_69_11.prototype._isValidNumber=function(a){var b=parseFloat(a);if(isNaN(b)||b<0)return false;return b==a};RichMediaCore_69_11.prototype.writeSurveyURL=function(a){if(!a.previewMode&&a.surveyUrl.length>0)document.write("<scr"+'ipt src="'+a.surveyUrl+'" language="JavaScript"></scr'+"ipt>")};RichMediaCore_69_11.prototype.postPublisherData=function(a,b){if(!a.previewMode&&this.isInterstitialCreative(a)&&b!=""){var c=new Image;c.src=b}};
RichMediaCore_69_11.prototype.isInterstitialCreative=function(a){return a.type==this.CREATIVE_TYPE_FLOATING||a.type==this.CREATIVE_TYPE_FLOATING_WITH_REMINDER||a.type==this.CREATIVE_TYPE_MULTI_FLOATING};RichMediaCore_69_11.prototype.isBrowserCompliant=function(a){return(this.isAndroid()&&this.getAndroidOSVersion()>2.1||(this.isOpera()||this.isInternetExplorer()||this.isFirefox()||this.isSafari()||this.isChrome())&&(this.isWindows()||this.isMac()||this.isLinux()))&&a>0&&this.getPluginInfo()>=a};
RichMediaCore_69_11.prototype.shouldDisplayFloatingAsset=function(a){return!this.isInternetExplorer()||this._convertDuration(a)||this.getIEVersion()>=5.5};RichMediaCore_69_11.prototype.isWindows=function(){return navigator.appVersion.indexOf("Windows")!=-1};
RichMediaCore_69_11.prototype.isFirefox=function(){var a=navigator.userAgent.toUpperCase();if(a.indexOf("GECKO")!=-1)if(a.indexOf("FIREFOX")!=-1){var b=parseFloat(a.substr(a.lastIndexOf("/")+1));return b>=1}else if(a.indexOf("NETSCAPE")!=-1){b=parseFloat(a.substr(a.lastIndexOf("/")+1));return b>=8}else return false;else return false};RichMediaCore_69_11.prototype.isOpera=function(){return navigator.userAgent.toUpperCase().indexOf("OPERA")!=-1};
RichMediaCore_69_11.prototype.isSafari=function(){var a="Safari";var b=navigator.userAgent.indexOf(a);var c=navigator.vendor!=undefined?navigator.vendor.toUpperCase():"";return navigator.appVersion.indexOf(a)!=-1&&parseFloat(navigator.userAgent.substring(b+a.length+1))>=312.6&&(c.indexOf("APPLE")!=-1||this.isAndroid()&&c.indexOf("GOOGLE")!=-1)};
RichMediaCore_69_11.prototype.isChrome=function(){var a=navigator.userAgent.toUpperCase();var b=navigator.vendor!=undefined?navigator.vendor.toUpperCase():"";return a.indexOf("CHROME")!=-1&&b.indexOf("GOOGLE")!=-1};RichMediaCore_69_11.prototype.isMac=function(){return navigator.appVersion.indexOf("Mac")!=-1};RichMediaCore_69_11.prototype.isLinux=function(){return navigator.appVersion.toUpperCase().indexOf("LINUX")!=-1||navigator.userAgent.toUpperCase().indexOf("LINUX")!=-1};
RichMediaCore_69_11.prototype.isInternetExplorer=function(){return navigator.appVersion.indexOf("MSIE")!=-1&&navigator.userAgent.indexOf("Opera")<0};RichMediaCore_69_11.prototype.isIPhone=function(){return navigator.userAgent.toUpperCase().indexOf("IPHONE")!=-1};RichMediaCore_69_11.prototype.isIPad=function(){return navigator.userAgent.toUpperCase().indexOf("IPAD")!=-1};RichMediaCore_69_11.prototype.isAndroid=function(){return navigator.userAgent.toUpperCase().indexOf("ANDROID")!=-1};
RichMediaCore_69_11.prototype.getAndroidOSVersion=function(){var a=navigator.userAgent.toUpperCase().indexOf("ANDROID");var b=navigator.userAgent.substring(a+"ANDROID".length+1);return parseFloat(b)};RichMediaCore_69_11.prototype.getAndroidBrowserVersion=function(){var a=navigator.userAgent.toUpperCase().indexOf("VERSION");var b=navigator.userAgent.substring(a+"VERSION".length+1);return parseFloat(b)};
RichMediaCore_69_11.prototype.getIEVersion=function(){var a=0;if(this.isInternetExplorer()){var b="MSIE ";var c=navigator.appVersion.indexOf(b)+b.length;var d=navigator.appVersion.substr(c);a=parseFloat(d.substring(0,d.indexOf(";")))}return a};RichMediaCore_69_11.prototype.getFirefoxVersion=function(){var a=navigator.userAgent.toUpperCase().indexOf("FIREFOX")+"FIREFOX".length+1;return parseFloat(navigator.userAgent.substring(a))};
RichMediaCore_69_11.prototype.getSafariVersion=function(){var a=navigator.userAgent.toUpperCase().indexOf("VERSION")+"VERSION".length+1;return parseFloat(navigator.userAgent.substring(a))};RichMediaCore_69_11.prototype.getChromeVersion=function(){var a=navigator.userAgent.toUpperCase().indexOf("CHROME")+"CHROME".length+1;return parseFloat(navigator.userAgent.substring(a))};RichMediaCore_69_11.prototype.isHTML5SupportedBrowser=function(){return!!document.createElement("canvas").getContext};
RichMediaCore_69_11.prototype.getPluginInfo=function(){return this.isInternetExplorer()&&this.isWindows()?this._getIeWindowsFlashPluginVersion():this._detectNonWindowsFlashPluginVersion()};
RichMediaCore_69_11.prototype._detectNonWindowsFlashPluginVersion=function(){var a=0;var b="Shockwave Flash";if(navigator.plugins&&(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins[b])){var c=navigator.plugins["Shockwave Flash 2.0"]?" 2.0":"";var d=navigator.plugins[b+c].description;var e=d.indexOf(b)+(b.length+1);var f=d.indexOf(".");var g=d.substring(e,f);var h=d.split(" ");var i=parseInt(h[h.length-1].replace(new RegExp("[A-Za-z]","g"),""));if(isNaN(i))i="0";a=parseFloat(g+"."+i);if(a>
6&&a<6.65)a=0}return a};
RichMediaCore_69_11.prototype._getIeWindowsFlashPluginVersion=function(){var a="";var b=0;var c=new Array;var d=new Array;var e="\r\n";var f=0;var g="swfVersion = "+f+e+"mtfIsOk = "+false+e+"On Error Resume Next"+e+'set motifSwfObject = CreateObject("ShockwaveFlash.ShockwaveFlash")'+e+"mtfIsOk = IsObject(motifSwfObject)"+e+"if mtfIsOk = true then"+e+'swfVersion = motifSwfObject.GetVariable("$version")'+e+"end if"+e+"";window.execScript(g,"VBScript");if(mtfIsOk){a=swfVersion;d=a.split(" ");if(d.length>
1){c=d[1].split(",");var h=c[0];var i=c[2];if(h>9&&c.length>3)i=c[c.length-1];b=parseFloat(h+"."+i)}}return b};RichMediaCore_69_11.prototype.trackBackupImageEvent=function(a){var b="eid1=9;ecn1=1;etm1=0;";var c=new Date;var d=document.createElement("IMG");d.src=a+"&timestamp="+c.getTime()+";"+b};
RichMediaCore_69_11.prototype.trackUrl=function(a,b,c){if(c||a=="")return;if(b){var d=document.createElement("IMG");d.style.visibility="hidden";d.style.width="0px";d.style.height="0px";d.src=a;d.onload=function(){this.parentNode.removeChild(this)};document.body.appendChild(d)}else document.write('<IMG SRC="'+a+'" style="display:none" onload="this.parentNode.removeChild(this)" width="0px" height="0px" alt="">')};
RichMediaCore_69_11.prototype.logThirdPartyImpression=function(a){this.trackUrl(a.thirdPartyImpUrl,false,a.previewMode)};RichMediaCore_69_11.prototype.logThirdPartyBackupImageImpression=function(a,b){this.trackUrl(a.thirdPartyBackupImpUrl,b,a.previewMode)};RichMediaCore_69_11.prototype.logThirdPartyRMImpression=function(a,b){this.trackUrl(a.thirdPartyFlashDisplayUrl,b,a.previewMode)};
RichMediaCore_69_11.prototype.isPartOfArrayPrototype=function(a){for(var b in Array.prototype)if(b==a)return true;return false};RichMediaCore_69_11.prototype.toObject=function(a){try{if(document.layers)return document.layers[a]?eval(document.layers[a]):null;else if(document.all&&!document.getElementById)return eval("window."+a)?eval("window."+a):null;else if(document.getElementById&&document.body.style)return document.getElementById(a)?eval(document.getElementById(a)):null}catch(b){}return null};
RichMediaCore_69_11.prototype.getCallbackObjectIndex=function(a){for(var b=0;b<dartCallbackObjects.length;b++)if(dartCallbackObjects[b]==a)return b;dartCallbackObjects[dartCallbackObjects.length]=a;return dartCallbackObjects.length-1};
RichMediaCore_69_11.prototype.registerPageLoadHandler=function(a,b){var c=this.generateGlobalCallback(a,b);if(document.readyState&&document.readyState=="complete"||this.isFirefox()&&this.isPageLoaded){c();return}if(this.isInternetExplorer())self.attachEvent("onload",c);else self.addEventListener("load",c,true)};RichMediaCore_69_11.prototype.pageLoaded=function(){RichMediaCore_69_11.prototype.isPageLoaded=true};
RichMediaCore_69_11.prototype.registerPageUnLoadHandler=function(a,b){var c=this.generateGlobalCallback(a,b);if(this.isInternetExplorer()&&this.isWindows())self.attachEvent("onunload",c);else if(this.isFirefox()||this.isSafari()||this.isChrome()||this.isOpera())self.addEventListener("unload",c,true)};RichMediaCore_69_11.prototype.registerTimeoutHandler=function(a,b,c){window.setTimeout(this.generateGlobalCallback(b,c),a)};
RichMediaCore_69_11.prototype.createFunction=function(a,b,c){var d="dartCallbackObjects["+this.getCallbackObjectIndex(b)+"]."+a+"(";for(var e=0;e<c.length;e++){d+="dartCallbackObjects["+this.getCallbackObjectIndex(c[e])+"]";if(e!=c.length-1)d+=","}d+=")";return new Function(d)};RichMediaCore_69_11.prototype.generateGlobalCallback=function(a,b){if(b){var c=this.getCallbackObjectIndex(b);a="if(dartCallbackObjects["+c+"] != null) dartCallbackObjects["+c+"]."+a}return new Function(a)};
RichMediaCore_69_11.prototype.registerEventHandler=function(a,b,c,d){var e=this.generateGlobalCallback(c,d);if(this.isInternetExplorer()&&this.isWindows())self.attachEvent("on"+a,e);else if(this.isFirefox()||this.isSafari()||this.isChrome()||this.isOpera())b.addEventListener(a,e,false)};RichMediaCore_69_11.prototype.scheduleCallbackOnLoad=function(a){var b=200;if(window.document.readyState.toLowerCase()=="complete")eval(a);else this.registerTimeoutHandler(b,"scheduleCallbackOnLoad('"+a+"')",this)};
RichMediaCore_69_11.prototype.getStyle=function(a){if(window.getComputedStyle)return window.getComputedStyle(a,"");else if(a.currentStyle)return a.currentStyle;else return a.style};
RichMediaCore_69_11.prototype.getWindowDimension=function(){var a=new Object;if(document.documentElement&&document.compatMode=="CSS1Compat"){a.width=document.documentElement.clientWidth;a.height=document.documentElement.clientHeight}else if(document.body&&(document.body.clientWidth||document.body.clientHeight)&&!this.isSafari()){a.width=document.body.clientWidth;a.height=document.body.clientHeight}else if(typeof window.innerWidth=="number"){a.width=window.innerWidth;a.height=window.innerHeight}return a};
RichMediaCore_69_11.prototype.getScrollbarPosition=function(){var a=new Object;a.scrollTop=0;a.scrollLeft=0;if(typeof window.pageYOffset=="number"){a.scrollTop=window.pageYOffset;a.scrollLeft=window.pageXOffset}else if(document.body&&(document.body.scrollLeft||document.body.scrollTop)){a.scrollTop=document.body.scrollTop;a.scrollLeft=document.body.scrollLeft}else if(document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)){a.scrollTop=document.documentElement.scrollTop;
a.scrollLeft=document.documentElement.scrollLeft}return a};RichMediaCore_69_11.prototype.isInFriendlyIFrame=function(){return this.isWindowAccessible(self.parent)};RichMediaCore_69_11.prototype.isWindowAccessible=function(a){try{a.document.body;return true}catch(b){return false}};RichMediaCore_69_11.prototype.isInMsnFriendlyIFrame=function(){return typeof inDapIF!="undefined"&&inDapIF};RichMediaCore_69_11.prototype.isInAolFriendlyIFrame=function(){return typeof inFIF!="undefined"&&inFIF};
RichMediaCore_69_11.prototype.isInMsnAjaxEnvironment=function(){return typeof inDapMgrIf!="undefined"&&inDapMgrIf};RichMediaCore_69_11.prototype.isInYahooFriendlyIFrame=function(){return typeof isAJAX!="undefined"&&isAJAX};RichMediaCore_69_11.prototype.isInClientPreviewIFrame=function(){if(typeof StudioPreviewResponse!="undefined")return!(new StudioPreviewResponse).isAdslotDetected;else return false};
RichMediaCore_69_11.prototype.isInAdSenseIFrame=function(){return typeof IN_ADSENSE_IFRAME!="undefined"&&IN_ADSENSE_IFRAME};RichMediaCore_69_11.prototype.isInWinLiveAPIPlatform=function(){try{return window["$WLXRmAd"]||window.parent&&window.parent["$WLXRmAd"]}catch(a){return false}};RichMediaCore_69_11.prototype.isInYahooCrossDomainIframe=function(){try{return window.Y&&Y.SandBox?Y.SandBox.vendor||null:null}catch(a){return false}};
RichMediaCore_69_11.prototype.checkDimension=function(a){if(typeof a=="number")return a+"px";else return a+(a!=""&&a!="auto"&&a.indexOf("px")<0?"px":"")};RichMediaCore_69_11.prototype.setFlashVariable=function(a,b,c,d){if(a==1)b.SetVariable("_root."+c,d);else{if(!b.changeInputVariable)this.createExternalInterfaceCallbackAccessor(b,"changeInputVariable");b.changeInputVariable(c,d)}};
RichMediaCore_69_11.prototype.getFlashVariable=function(a,b,c){if(a==1)return b.GetVariable("_root."+c);else{if(!b.getFlashVariable)this.createExternalInterfaceCallbackAccessor(b,"getFlashVariable");return b.getFlashVariable(c)}};RichMediaCore_69_11.prototype.createExternalInterfaceCallbackAccessor=function(a,b){if(a[b])return;a[b]=function(){return this.CallFunction('<invoke name="'+b+'" returntype="javascript">'+__flash__argumentsToXML(arguments,0)+"</invoke>")}};
RichMediaCore_69_11.prototype.getSalign=function(a,b,c,d,e,f){var g="";if(c==0&&f!=b)g+="T";else if(c!=0&&f==b)g+="B";if(d==0&&e!=a)g+="L";else if(d!=0&&e==a)g+="R";if((g=="T"||g=="B")&&(d!=0||e!=a))return"";if((g=="L"||g=="R")&&(c!=0||f!=b))return"";return g};RichMediaCore_69_11.prototype.usesSalignForExpanding=function(a,b){return(this.isMac()&&(this.isSafari()||this.isFirefox())||this.isWindows()&&this.isFirefox()&&b.toLowerCase()=="window")&&a.length>0};
RichMediaCore_69_11.prototype.unclipFlashObject=function(a,b,c,d){this.clipFlashObject(a,b,c,"auto","auto","auto","auto",d)};
RichMediaCore_69_11.prototype.clipFlashObject=function(a,b,c,d,e,f,g,h){b=this.checkDimension(b);c=this.checkDimension(c);d=this.checkDimension(d);e=this.checkDimension(e);f=this.checkDimension(f);g=this.checkDimension(g);var i=this.isMac()&&this.isSafari();var j=(this.isLinux()||this.isMac())&&this.isChrome();var m=this.isMac()&&this.isFirefox()&&this.getFirefoxVersion()>=11;if(h||!(i&&(this.getSafariVersion()>5||a.pushContents))&&this.usesSalignForExpanding(a.salign,a.wmode)&&!m){var n=(h?"IFRAME_":
"FLASH_")+a.variableName;var k=this.toObject(n);if(k){k.style.width=b;k.style.height=c;k.width=b;k.height=c;k.style.marginLeft=g=="auto"?"0px":g;k.style.marginTop=d=="auto"?"0px":d}}var l=this.toObject("DIV_"+a.variableName);if(l){if(i||j){l.style.height=c;l.style.width=b}l.style.clip="rect("+d+" "+e+" "+f+" "+g+")"}if(a.pushContents&&this.getIEVersion()>=8)this.redrawIE8ForPushdown()};
RichMediaCore_69_11.prototype.redrawIE8ForPushdown=function(){var a=document.body.style.display;document.body.style.display="block";document.body.style.display=a};RichMediaCore_69_11.prototype.getSitePageUrl=function(a){if(a.type==this.CREATIVE_TYPE_INPAGE_WITH_OVERLAY)return"";if(a.previewMode)return a.livePreviewSiteUrl;else if(a.type==this.CREATIVE_TYPE_INPAGE&&a.servingMethod=="i")return self.document.referrer;else return self.location.href};
RichMediaCore_69_11.prototype.getElementPosition=function(a){var b=new Object;if(a.getBoundingClientRect){b.left=a.getBoundingClientRect().left;b.top=a.getBoundingClientRect().top}else{b.left=0;b.top=0;if(a.offsetParent){do{b.left+=a.offsetLeft;b.top+=a.offsetTop}while(a=a.offsetParent)}var c=this.getScrollbarPosition();b.top-=c.scrollTop;b.left-=c.scrollLeft}return b};
RichMediaCore_69_11.prototype.isFlashObjectReady=function(a,b,c){if(a==1)return b&&typeof b.PercentLoaded!="undefined"&&b.PercentLoaded()>0&&this.getAsset(c).conduitInitialized;else return b!=null&&typeof b.changeInputVariable!="undefined"};RichMediaCore_69_11.prototype.getSiteHost=function(a){var b="";if(a.length>=7&&a.substr(0,7)=="http://")b=a.substr(7);else if(a.length>=8&&a.substr(0,8)=="https://")b=a.substr(8);else b=a;var c=b.indexOf("/");if(c>0)b=b.substr(0,c);return b};
RichMediaCore_69_11.prototype.getSiteProtocol=function(a){var b="";if(a.length>=5&&a.substr(0,5)=="http:")b="http:";else if(a.length>=6&&a.substr(0,6)=="https:")b="https:";else b="http:";return b};
function RichMediaCreativeDisplayManager_69_11(a,b){this.creative=a;this.creativeIdentifier=a.creativeIdentifier;this.previewMode=a.previewMode;this.debugEventsMode=a.debugEventsMode;this.renderingId=a.renderingId;this.creativeType=a.type;this.mtfNoFlush=a.mtfNoFlush;this.dartPopupArray=new Object;this.isDisplayTimerRunning=false;this.fsCommandHandlers=new Object;this.rootElementArray=new Array;this.sourceIframe=typeof b!="undefined"?b:null;this.overlay=null;this.dartEventBin=null;this.previewHandler=
null;this.shouldLogInteractiveImpression=true;this.customTimerArray=new Object;this.assetState=new Object;this.importantEventArray=new Array(this.STANDARD_EVENT_INTERACTIVE_IMPRESSION,this.STANDARD_EVENT_VIDEO_PLAY,this.STANDARD_EVENT_VIDEO_VIEW_COMPLETE,this.STANDARD_EVENT_EXPAND_TIMER,this.STANDARD_EVENT_DYNAMIC_CREATIVE_IMPRESSION,this.STANDARD_EVENT_HTML5_CREATIVE_IMPRESSION);this.adListener=null;this.init(a);dartMotifAds[dartMotifAds.length]=this.creative}
RichMediaCreativeDisplayManager_69_11.prototype=new RichMediaCore_69_11;
RichMediaCreativeDisplayManager_69_11.prototype.init=function(a){this.buildImportantEventList(a);this.createEventBin(a);this.assets=new Object;if(this.creative.assets["floatAssets"])for(var b=0;b<this.creative.assets["floatAssets"].length;b++){var c=this.creative.assets["floatAssets"][b];this.assets[c.variableName]=c}else for(var d in this.creative.assets)if(!this.isPartOfArrayPrototype(d)){c=this.creative.assets[d];this.assets[c.variableName]=c}if(a.type==this.CREATIVE_TYPE_FLOATING_WITH_REMINDER||
a.type==this.CREATIVE_TYPE_INPAGE_WITH_FLOATING||a.type==this.CREATIVE_TYPE_MULTI_FLOATING||a.type==this.CREATIVE_TYPE_INPAGE_WITH_OVERLAY)this.dualAssetManager=new DualAssetManager_69_11(a,this);if(a.type==this.CREATIVE_TYPE_EXPANDING||a.type==this.CREATIVE_TYPE_FLOATING||a.type==this.CREATIVE_TYPE_FLOATING_WITH_REMINDER||a.type==this.CREATIVE_TYPE_MULTI_FLOATING||a.type==this.CREATIVE_TYPE_INPAGE_WITH_FLOATING)this.pageElementsManager=new PageElementsManager_69_11(a,this)};
RichMediaCreativeDisplayManager_69_11.prototype.buildImportantEventList=function(a){for(var b=0;b<this.importantEventArray.length;b++)this.importantEventArray[b]=this.getStandardEventId(this.importantEventArray[b]);for(var c in a.videoComponents)if(!this.isPartOfArrayPrototype(c)){this.importantEventArray[this.importantEventArray.length]=this.getCustomVideoEventId("Count",c,this.STANDARD_EVENT_VIDEO_PLAY);this.importantEventArray[this.importantEventArray.length]=this.getCustomVideoEventId("Count",
c,this.STANDARD_EVENT_VIDEO_VIEW_COMPLETE)}for(var d in a.exitEvents)if(!this.isPartOfArrayPrototype(d))this.importantEventArray[this.importantEventArray.length]=this.getEventId("Exit",d)};
RichMediaCreativeDisplayManager_69_11.prototype.createEventBin=function(a){if(!this.previewMode)this.dartEventBin=new RichMediaEventBin_69_11(this.creativeIdentifier,this.mtfNoFlush,this.importantEventArray);else if(this.debugEventsMode){this.initDebugHandler(a);var b=this.getSourceIframe();if(typeof DebugEventBin_69_11!="undefined")this.dartDebugEventBin=new DebugEventBin_69_11(this.creativeIdentifier,this.previewHandler);else if(this.isServedInIframe()&&typeof b.contentWindow.DebugEventBin_69_11!=
"undefined")this.dartDebugEventBin=new b.contentWindow.DebugEventBin_69_11(this.creativeIdentifier,this.previewHandler)}};RichMediaCreativeDisplayManager_69_11.prototype.initDebugHandler=function(a){try{if(typeof DARTDebugEventHandler!="undefined")this.previewHandler=new DARTDebugEventHandler;else if(typeof self.parent.DARTDebugEventHandler!="undefined"){self.parent.globalTemplatePreviewHandler=new self.parent.DARTDebugEventHandler;this.previewHandler=self.parent.globalTemplatePreviewHandler}}catch(b){}};
RichMediaCreativeDisplayManager_69_11.prototype.deleteCreative=function(a){this.deleteJSObjects();if(!a)this.deleteHTMLObjects()};RichMediaCreativeDisplayManager_69_11.prototype.deleteHTMLObjects=function(){for(var a=0;a<this.rootElementArray.length;a++)if(this.rootElementArray[a]!=null&&this.rootElementArray[a].parentNode!=null)this.removeChildNode(this.rootElementArray[a],this.rootElementArray[a].parentNode)};
RichMediaCreativeDisplayManager_69_11.prototype.deleteJSObjects=function(){if(this.creative.isInterstitial)DoNotDisplayIA=null;this.detachFSCommandHandler();this.setShouldFlush(this.renderingId,false);this.removeArrayElement(dartCallbackObjects,this.dartEventBin);this.dartEventBin=null};RichMediaCreativeDisplayManager_69_11.prototype.removeArrayElement=function(a,b){for(var c=0;c<a.length;c++)if(a[c]==b)a[c]=null};
RichMediaCreativeDisplayManager_69_11.prototype.fsHook=function(a){var b="dartCreativeDisplayManagers['"+this.creativeIdentifier+"'].fsHook('"+a+"');";if(!this.toObject(a)){window.setTimeout(b,100);return}var c="";c+=a+"_DoFSCommand = function(command, args) { \n";c+='    if(dartCreativeDisplayManagers["'+this.creativeIdentifier+'"] != null) dartCreativeDisplayManagers["'+this.creativeIdentifier+'"].FSCommandHandler(command, args, "'+a+'");\n';c+="}\n";window.eval(c);if(this.isInternetExplorer()){var d=
this.toObject(a);var e=eval(a+"_DoFSCommand");this.fsCommandHandlers[a]=e;if(d.attachEvent("FSCommand",e))this.registerPageUnLoadHandler("detachFSCommandHandler()",this)}};RichMediaCreativeDisplayManager_69_11.prototype.registerFSCommandHandler=function(a){if(this.isInternetExplorer()){var b=this.toObject("FLASH_"+a);var c=this.fsCommandHandlers["FLASH_"+a];if(b.attachEvent("FSCommand",c))this.registerPageUnLoadHandler("detachFSCommandHandler()",this)}};
RichMediaCreativeDisplayManager_69_11.prototype.detachFSCommandHandler=function(){for(var a in this.assets)if(!this.isPartOfArrayPrototype(a)){var b="FLASH_"+a;var c=this.toObject(b);var d=this.fsCommandHandlers[b];if(c!=null)if(this.isInternetExplorer())c.detachEvent("FSCommand",d)}};
RichMediaCreativeDisplayManager_69_11.prototype.FSCommandHandler=function(a,b,c){if(a=="mtfCommands"){var d=b.split("&");c=c.substr(c.indexOf("_")+1,c.length);for(var e=0;e<d.length;e++){var f=this._parseCommandString(d[e]);this.storeCustomTimers(f.argArray,c);var g=this.createFunctionCall(f.command,f.argArray);try{eval('dartCreativeDisplayManagers["'+this.creativeIdentifier+'"].'+g)}catch(h){g=f.command+"('"+f.argString+"')";try{eval(g)}catch(i){}}}}else{var j=this._splitArgs(b);g=this.createFunctionCall(a,
j);try{return eval('dartCreativeDisplayManagers["'+this.creativeIdentifier+'"].'+g)}catch(m){try{eval(g)}catch(n){}}}};
RichMediaCreativeDisplayManager_69_11.prototype.storeCustomTimers=function(a,b){if(a[0]=="Start"&&a[4]=="true"){if(!this.customTimerArray[b])this.customTimerArray[b]=new Array;if(!this.assetState[b])this.assetState[b]=new Object;this.assetState[b].isAssetExpanded=true;if(this.isCustomTimerExisting(this.customTimerArray[b],a[1]))this.customTimerArray[b][this.customTimerArray[b].length]=a}if(a[0]=="Stop"&&a[4]=="true"){if(!this.assetState[b])this.assetState[b]=new Object;this.assetState[b].isAssetExpanded=
false}if(unescape(a[1])=="EVENT_MANUAL_CLOSE")if(this.assetState[b])this.assetState[b].isAssetExpanded=false};RichMediaCreativeDisplayManager_69_11.prototype.isCustomTimerExisting=function(a,b){if(a)for(var c=0;c<a.length;c++)if(a[c][1]==b)return false;return true};RichMediaCreativeDisplayManager_69_11.prototype.setFocus=function(a){var b=this.toObject("FLASH_"+a);if(b!=null)if(this.isFirefox()&&this.isMac()){var c=this.getFireFoxVersion();if(c>=2&&c<3){b.blur();window.blur()}}};
RichMediaCreativeDisplayManager_69_11.prototype.reportCustomVariable=function(a,b){if(!this.previewMode){var c=this.creative.stringPostingUrl;var d=new Date;c+="&timestamp="+d.getTime()+";"+"str="+unescape(a)+";"+"strtype="+b;var e=document.createElement("img");e.src=c}else{var f=this.getEventBin();if(f!=null)f.logCustomVariable(unescape(a),b,this.creative.renderingId)}};
RichMediaCreativeDisplayManager_69_11.prototype.setDynamicServeId=function(a){var b=this.getEventBin();if(b){b.setDynamicServeId(a);var c=this.getStandardEventId(this.STANDARD_EVENT_DYNAMIC_CREATIVE_IMPRESSION);b.logMetEvent("Count",c,this.creative.renderingId,false,this.STANDARD_EVENT_DYNAMIC_CREATIVE_IMPRESSION);b.flushMetCounters(this.creative.renderingId)}};
RichMediaCreativeDisplayManager_69_11.prototype.getFireFoxVersion=function(){var a=navigator.userAgent.toUpperCase();if(a.indexOf("GECKO")!=-1)if(a.indexOf("FIREFOX")!=-1)return parseFloat(a.substr(a.lastIndexOf("/")+1));return null};
RichMediaCreativeDisplayManager_69_11.prototype.conduitInitialized=function(a){if(this.creative.shouldDisplayHTML5Asset){this.dispatchPageLoadToEnabler();this.setAdParameters()}else{RichMediaCore_69_11.prototype.trackCsiEvent("fe");var b=this.getAsset(a);b.conduitInitialized=true;if(this.shouldCsi(b,this.creative.type))RichMediaCore_69_11.prototype.reportCsi(this.creative)}};
RichMediaCreativeDisplayManager_69_11.prototype.setTimerAdjustment=function(a,b,c){this.getEventBin().setTimerAdjustment(a,b,c)};RichMediaCreativeDisplayManager_69_11.prototype.getEventBin=function(){if(!this.previewMode)return this.dartEventBin;else if(this.debugEventsMode)return this.dartDebugEventBin;else return null};RichMediaCreativeDisplayManager_69_11.prototype.getStandardEventId=function(a){return this.creative.standardEvents[a].reportingId};
RichMediaCreativeDisplayManager_69_11.prototype.getEventId=function(a,b){var c;if(a=="Start"||a=="Stop")c=this.creative.timerEvents[b];else if(a=="Count")c=this.creative.counterEvents[b];else if(a=="Exit")c=this.creative.exitEvents[b];return c!=null?c.reportingId:-1};RichMediaCreativeDisplayManager_69_11.prototype.evaluateBoolean=function(a){var b=typeof a;return b=="string"&&a=="true"||b=="boolean"&&a};
RichMediaCreativeDisplayManager_69_11.prototype.skipEventlogging=function(a,b){if(this.isInAdSenseIFrame()&&this.creative.type==this.CREATIVE_TYPE_EXPANDING){if(b==this.STANDARD_EVENT_EXPAND_TIMER&&a=="Start")return true;var c=this.creative.assets[this.ASSET_TYPE_EXPANDING].variableName;if(this.customTimerArray[c])for(var d=0;d<this.customTimerArray[c].length;d++)if(unescape(this.customTimerArray[c][d][1])==b&&a=="Start")return true}return false};
RichMediaCreativeDisplayManager_69_11.prototype.logEvent=function(a,b,c,d,e,f){var g;b=unescape(b);if(typeof f=="undefined"&&this.skipEventlogging(a,b))return;e=this.evaluateBoolean(e);d=this.evaluateBoolean(d);if(b=="EVENT_USER_INTERACTION"){if(this.previewMode&&!this.shouldLogInteractiveImpression)return;this.shouldLogInteractiveImpression=false}if(b=="EXPAND_TIMER"&&a=="Stop"||b=="EVENT_MANUAL_CLOSE")for(var h in this.assetState)if(this.assetState[h].isAssetExpanded)return;if(e)g=this.getEventId(a,
b);else g=this.getStandardEventId(b);if(g==-1)return;if(a==="Exit")a="Count";if(b==this.STANDARD_EVENT_DISPLAY_TIMER)this.logDisplayTimerEvent(a,c);else{var i=this.getEventBin();if(i)i.logMetEvent(a,g,c,d,b)}};
RichMediaCreativeDisplayManager_69_11.prototype.getCustomVideoEventId=function(a,b,c){var d=this.getStandardEventId(c);var e;if(a=="Start"||a=="Stop")e=this.creative.timerEvents;else e=this.creative.counterEvents;var f="";for(var g in e){var h=e[g];if(h.sourceComponentName==b&&h.sourceStandardEventId==d){f=h.reportingId;break}}return f};
RichMediaCreativeDisplayManager_69_11.prototype.logVideoEvent=function(a,b,c){b=unescape(b);var d=this.creative.videoComponents[b];var e=this.getEventBin();var f=this.getStandardEventId(c);if(e)e.logMetEvent(a,f,this.creative.renderingId,false,c);if(d.trackCustomEvents){var g=this.getCustomVideoEventId(a,b,c);if(e)e.logMetEvent(a,g,this.creative.renderingId,false,c)}};
RichMediaCreativeDisplayManager_69_11.prototype.stopStandardTimers=function(a){this.logEvent("Stop",this.STANDARD_EVENT_DISPLAY_TIMER,a);this.logEvent("Stop",this.STANDARD_EVENT_VIDEO_VIEW_TIMER,a)};
RichMediaCreativeDisplayManager_69_11.prototype.stopCustomTimers=function(a,b){if(this.customTimerArray[a]){for(var c=0;c<this.customTimerArray[a].length;c++){this.logEvent("Stop",this.customTimerArray[a][c][1],b,this.customTimerArray[a][c][3],this.customTimerArray[a][c][4]);this.removeArrayElement(this.customTimerArray[a],this.customTimerArray[a][c])}this.customTimerArray[a]=null}if(this.assetState[a])this.assetState[a].isAssetExpanded=false;for(var d in this.assetState)if(this.assetState[d].isAssetExpanded)return;
this.logEvent("Stop",this.STANDARD_EVENT_EXPAND_TIMER,b)};RichMediaCreativeDisplayManager_69_11.prototype.logDisplayTimerEvent=function(a,b){var c=this.getEventBin();if(a=="Start"){if(!this.isDisplayTimerRunning){if(c)c.logMetEvent("Start","2",b);this.isDisplayTimerRunning=true}}else if(a=="Stop")if(this.isDisplayTimerRunning){if(c)c.logMetEvent("Stop","2",b);this.isDisplayTimerRunning=false}};RichMediaCreativeDisplayManager_69_11.prototype.flushCounters=function(a){var b=this.getEventBin();if(b)b.flushMetCounters(a)};
RichMediaCreativeDisplayManager_69_11.prototype.scheduleTurnOffEventBinFlushing=function(a,b){var c=this.getEventBin();if(c)this.registerTimeoutHandler(b*1000,"turnOffFlushing('"+a+"')",c)};RichMediaCreativeDisplayManager_69_11.prototype.setShouldFlush=function(a,b){var c=this.getEventBin();if(c)c.setMetShouldFlush(a,b)};RichMediaCreativeDisplayManager_69_11.prototype.getShouldFlush=function(a){var b=this.getEventBin();return b&&b.getShouldFlush(a)};
RichMediaCreativeDisplayManager_69_11.prototype.registerUrl=function(a,b){var c=this.getEventBin();if(c)c.registerEventBinUrl(a,b)};RichMediaCreativeDisplayManager_69_11.prototype.logExitEventFlushCounters=function(a,b,c,d){this.logEvent("Exit",a,b,c,d);this.flushCounters(b)};RichMediaCreativeDisplayManager_69_11.prototype.logEventFlushCounters=function(a,b,c,d,e){this.logExitEventFlushCounters(b,c,d,e)};
RichMediaCreativeDisplayManager_69_11.prototype._logEventFlushCountersOpenPopup=function(a,b,c,d,e,f,g){this.logEvent(a,b,c,true);this.flushCounters(c);this.openPopup(d,e,f,g)};RichMediaCreativeDisplayManager_69_11.prototype.getExitUrl=function(a,b){var c=b==undefined?this.creative.exitEvents[a].url:b;var d=this.creative.clickThroughUrl;var e=this.creative.clickN!=""?parseInt(this.creative.clickN):1;if(d.indexOf("?")>=0||d.indexOf("&")>=0)for(var f=0;f<e;f++)c=escape(c);return d+c};
RichMediaCreativeDisplayManager_69_11.prototype.logInteractiveImpression=function(){if(!this.interactiveImpressionLogged){this.logEvent("Count",this.STANDARD_EVENT_INTERACTIVE_IMPRESSION);this.interactiveImpressionLogged=true}};
RichMediaCreativeDisplayManager_69_11.prototype.logExitFlushEventsOpenPopup=function(a,b,c,d,e,f){var g=this.creative.exitEvents[b];var h=this.getExitUrl(b);e=e=="null"?null:e;f=f=="null"?null:f;if(e)h=this.getExitUrl(b,e);else if(f!=null&&f!=""){h=h.indexOf("?")!=-1&&f.charAt(0)!="&"&&h.charAt(h.length-1)!="?"?h+"&":h;h=h.indexOf("?")==-1&&f.indexOf("?")==-1?h+"?":h;h+=f}this.logInteractiveImpression();this.logExitEventFlushCounters(b,c,true,true);if(g.customizedWindow)this.openPopup(h,"motifWindow",
g.windowFeatures,false);else this.openPopup(h,"motifWindow",null,false)};RichMediaCreativeDisplayManager_69_11.prototype.setExpandingManager=function(a){this.expandingManager=a};RichMediaCreativeDisplayManager_69_11.prototype.hasExpandingManager=function(){return typeof this.expandingManager!="undefined"};RichMediaCreativeDisplayManager_69_11.prototype.setFloatingManager=function(a){this.floatingManager=a};
RichMediaCreativeDisplayManager_69_11.prototype.hasFloatingManager=function(){return typeof this.floatingManager!="undefined"};RichMediaCreativeDisplayManager_69_11.prototype.expandAsset=function(a){if(this.creative.shouldDisplayHTML5Asset)this.expandHTMLAsset(a);else this.expandFlashAsset(a)};
RichMediaCreativeDisplayManager_69_11.prototype.expandHTMLAsset=function(a){var b=this.getAsset(a);var c=b.expandedWidth!=undefined?b.expandedWidth:b.width;var d=b.expandedHeight!=undefined?b.expandedHeight:b.height;var e=this.creative.type==this.CREATIVE_TYPE_EXPANDING;if(e)this._adjustWindowElements(a,true);if(e&&b.pushContents)this.expandingManager.startAnimation(b,true,true);else this.unclipFlashObject(b,c,d,true)};
RichMediaCreativeDisplayManager_69_11.prototype.expandFlashAsset=function(a){var b=this.getAsset(a);var c=b.expandedWidth!=undefined?b.expandedWidth:b.width;var d=b.expandedHeight!=undefined?b.expandedHeight:b.height;var e=this.creative.type==this.CREATIVE_TYPE_EXPANDING;var f=this.toObject("FLASH_"+a);var g=this.hasExpandingManager()&&this.expandingManager.isMultiDirectionalExpanding(f);if(e&&!this.isInAdSenseIFrame()&&g)var h=this.expandingManager.getExpandingDirection(b);if(this.adListener)this.adListener.expand();
if(e)this._adjustWindowElements(a,true);if(e&&b.pushContents)this.expandingManager.startAnimation(b,true,false);else this.unclipFlashObject(b,c,d,false);if(this.isMac()&&this.isChrome()&&!b.pushContents)this.redrawForChrome(a);if(e&&g)if(this.isInAdSenseIFrame())this.expandingManager.creativeToolset.expandWindow();else this.multiDirectionExpand(f,h)};
RichMediaCreativeDisplayManager_69_11.prototype.multiDirectionExpand=function(a,b){try{this.setFlashVariable(this.creative.asVersion,a,"mde_expandedDirection",b)}catch(c){}};RichMediaCreativeDisplayManager_69_11.prototype.collapseAsset=function(a){if(this.creative.shouldDisplayHTML5Asset)this.collapseHTMLAsset(a);else this.collapseFlashAsset(a)};
RichMediaCreativeDisplayManager_69_11.prototype.collapseHTMLAsset=function(a){var b=this.getAsset(a);var c=b.collapsedWidth!=undefined?b.collapsedWidth:b.width;var d=b.collapsedHeight!=undefined?b.collapsedHeight:b.height;var e=this.creative.type==this.CREATIVE_TYPE_EXPANDING;if(e&&b.pushContents)this.expandingManager.startAnimation(b,false,true);else this.clipFlashObject(b,c,d,b.offsetTop,b.offsetRight,b.offsetBottom,b.offsetLeft,true);if(e)this._adjustWindowElements(a,false)};
RichMediaCreativeDisplayManager_69_11.prototype.collapseFlashAsset=function(a){var b=this.getAsset(a);var c=b.collapsedWidth!=undefined?b.collapsedWidth:b.width;var d=b.collapsedHeight!=undefined?b.collapsedHeight:b.height;var e=this.creative.type==this.CREATIVE_TYPE_EXPANDING;if(e&&b.pushContents)this.expandingManager.startAnimation(b,false,false);else this.clipFlashObject(b,c,d,b.offsetTop,b.offsetRight,b.offsetBottom,b.offsetLeft,false);if(this.isMac()&&this.isChrome()&&!b.pushContents)this.redrawForChrome(a);
if(e)this._adjustWindowElements(a,false);var f=this.toObject("FLASH_"+a);var g=this.hasExpandingManager()&&this.expandingManager.isMultiDirectionalExpanding(f);if(e&&g)if(this.isInAdSenseIFrame())this.expandingManager.creativeToolset.collapseWindow();else this.multiDirectionCollapse(f);if(this.adListener)this.adListener.collapse()};
RichMediaCreativeDisplayManager_69_11.prototype.redrawForChrome=function(a,b){var c=this.toObject("OUTER_DIV_"+a).style.zIndex;if(b!=undefined)this.toObject("OUTER_DIV_"+a).style.zIndex=b;else{this.toObject("OUTER_DIV_"+a).style.zIndex="999999";var d="dartCreativeDisplayManagers['"+this.creativeIdentifier+"'].redrawForChrome('"+a+"', '"+c+"');";window.setTimeout(d,10)}};
RichMediaCreativeDisplayManager_69_11.prototype.multiDirectionCollapse=function(a){try{this.setFlashVariable(this.creative.asVersion,a,"mde_expandedState","collapsed")}catch(b){}};RichMediaCreativeDisplayManager_69_11.prototype.onMouseOver=function(a){try{var b=this.toObject("FLASH_"+a);this.setFlashVariable(this.creative.asVersion,b,"isMouseOver","1")}catch(c){}};
RichMediaCreativeDisplayManager_69_11.prototype.onMouseOut=function(a){try{var b=this.toObject("FLASH_"+a);this.setFlashVariable(this.creative.asVersion,b,"isMouseOver","0")}catch(c){}};RichMediaCreativeDisplayManager_69_11.prototype.onMouseOverHtml5=function(a){try{this.invokeEnablerFunction("setParameter",["isMouseOver","1"],a)}catch(b){}};RichMediaCreativeDisplayManager_69_11.prototype.onMouseOutHtml5=function(a){try{this.invokeEnablerFunction("setParameter",["isMouseOver","0"],a)}catch(b){}};
RichMediaCreativeDisplayManager_69_11.prototype.onTouchHtml5=function(a){try{this.invokeEnablerFunction("setParameter",["isMouseOver","1"],a)}catch(b){}};RichMediaCreativeDisplayManager_69_11.prototype.onTouchEndHtml5=function(a){try{this.invokeEnablerFunction("setParameter",["isMouseOver","0"],a)}catch(b){}};RichMediaCreativeDisplayManager_69_11.prototype.scheduleCallbackOnLoad=function(a){a='dartCreativeDisplayManagers["'+this.creativeIdentifier+'"].'+a;this.registerPageLoadHandler(a,null)};
RichMediaCreativeDisplayManager_69_11.prototype.scheduleDisplay=function(a,b,c){b=this._convertDuration(b);if(c)this._adjustWindowElements(a,true);if(b=="AUTO")this.registerTimeoutHandler(1000,"_autoStopPlaying('"+a+"')",this);else if(b>0)this.registerTimeoutHandler(eval(b)*1000,"stopDisplay('"+a+"')",this)};RichMediaCreativeDisplayManager_69_11.prototype.tellCompanionAssetStop=function(a){this.dualAssetManager.tellCompanionAssetStop(a)};
RichMediaCreativeDisplayManager_69_11.prototype.tellCompanionAssetStart=function(a){this.dualAssetManager.tellCompanionAssetStart(a)};RichMediaCreativeDisplayManager_69_11.prototype.tellCompanionAssetHide=function(a){this.dualAssetManager.tellCompanionAssetHide(a)};RichMediaCreativeDisplayManager_69_11.prototype.tellCompanionAssetShow=function(a){this.dualAssetManager.tellCompanionAssetShow(a)};
RichMediaCreativeDisplayManager_69_11.prototype.getAsset=function(a){if(this.creative.assets["floatAssets"])for(var b=0;b<this.creative.assets["floatAssets"].length;b++){var c=this.creative.assets["floatAssets"][b];if(c.variableName==a)return c}else for(var d in this.creative.assets)if(!this.isPartOfArrayPrototype(d)&&this.creative.assets[d].variableName==a)return this.creative.assets[d];return null};
RichMediaCreativeDisplayManager_69_11.prototype.getHTML5Asset=function(){for(var a in this.creative.assets)if(!this.isPartOfArrayPrototype(a))return this.creative.assets[a];return null};RichMediaCreativeDisplayManager_69_11.prototype.tellAssetHide=function(a){var b=this.getAssetType(a);if(b==this.ASSET_TYPE_OVERLAY)this.closePopupAsset(a);else this.stopDisplay(a)};RichMediaCreativeDisplayManager_69_11.prototype.tellAssetShow=function(a){this._startDisplay(a,false)};
RichMediaCreativeDisplayManager_69_11.prototype.tellAssetStart=function(a){if(this.isFlashScriptingSupported())this.playFlash(a)};RichMediaCreativeDisplayManager_69_11.prototype.tellAssetStop=function(a){var b=this.toObject("FLASH_"+a);if(b&&this.isFlashScriptingSupported())b.StopPlay()};RichMediaCreativeDisplayManager_69_11.prototype.tellAssetGotoFrame=function(a,b){var c=this.toObject("FLASH_"+a);if(c&&this.isFlashScriptingSupported())c.GotoFrame(b)};
RichMediaCreativeDisplayManager_69_11.prototype.isAssetPlaying=function(a){var b=this.toObject("FLASH_"+a);if(b&&this.isFlashScriptingSupported())return b.IsPlaying();return false};
RichMediaCreativeDisplayManager_69_11.prototype.replayAsset=function(a){var b=this.toObject("DIV_"+a);if(b&&b.style.visibility!="visible"){b.style.visibility="visible";var c=this.getAsset(a);if(c!=null){var d=this.toObject("FLASH_"+a);d.Rewind();d.StopPlay();this.scheduleDisplay(a,c.duration,true);if(c.isMainAsset){var e=this.getRenderingId(a);this.logEvent("Start","DISPLAY_TIMER",e)}}}};
RichMediaCreativeDisplayManager_69_11.prototype.openPopup=function(a,b,c,d){if(c)var e=window.open(a,b,c);else e=window.open(a,b);this.dartPopupArray[b]=e;if(eval(d))window.focus();return e};
RichMediaCreativeDisplayManager_69_11.prototype.notifyPreviewHandler=function(a,b){if(this.creative.debugEventsMode&&this.previewHandler)try{if(b=="startDisplay"){var c=this.generateGlobalCallback("replayAsset('"+a.variableName+"')",this);this.previewHandler.onAssetDisplayed("DIV_"+a.variableName,a.assetType,c)}else if(b=="stopDisplay")this.previewHandler.onBeforeAssetRemoved("DIV_"+a.variableName,a.assetType)}catch(d){}};
RichMediaCreativeDisplayManager_69_11.prototype.stopDisplay=function(a){var b=this.toObject("DIV_"+a);if(b.style.visibility=="hidden")return;var c=this.getAsset(a);this.notifyPreviewHandler(c,"stopDisplay");var d=this.toObject("FLASH_"+a);if(!d)d=this.toObject("IFRAME_"+a);var e=this.creative.renderingId;if(c.isMainAsset&&!this.isAnyMainAssetPlaying(a))this.stopStandardTimers(e);this.logEvent("Stop",this.STANDARD_EVENT_INTERACTION_TIMER,e);this.stopCustomTimers(a,e);this.flushCounters(e);if(!this.isAnyCompanionVisible(a))this.scheduleTurnOffEventBinFlushing(e,
2);b.removeChild(d);b.style.visibility="hidden";this._adjustWindowElements(a,false)};RichMediaCreativeDisplayManager_69_11.prototype.isAnyMainAssetPlaying=function(a){for(var b in this.assets)if(!this.isPartOfArrayPrototype(b)&&b!=a){var c=this.toObject("DIV_"+b);if(c&&c.style.visibility=="visible"&&this.assets[b].isMainAsset)return true}return false};
RichMediaCreativeDisplayManager_69_11.prototype.isAssetVisible=function(a){var b=this.toObject("DIV_"+a);if(b&&b.style.visibility=="visible")return true;return false};RichMediaCreativeDisplayManager_69_11.prototype.isAnyCompanionVisible=function(a){for(var b in this.assets)if(!this.isPartOfArrayPrototype(b)&&b!=a){var c=this.toObject("DIV_"+b);if(c&&c.style.visibility=="visible")return true}return false};
RichMediaCreativeDisplayManager_69_11.prototype.addEntityProperties=function(a,b,c,d,e,f,g){this.pageElementsManager.addEntityProperties(a,b,c,d,e,f,g)};RichMediaCreativeDisplayManager_69_11.prototype.doNotAdjustIFrame=function(a,b){this.pageElementsManager.doNotAdjustIFrame(a,b)};RichMediaCreativeDisplayManager_69_11.prototype.doNotAdjustObject=function(a,b){this.pageElementsManager.doNotAdjustObject(a,b)};
RichMediaCreativeDisplayManager_69_11.prototype.getRenderingId=function(a){var b=a.split("_");return b.length>1?b[0]:null};RichMediaCreativeDisplayManager_69_11.prototype.createFunctionCall=function(a,b){var c=a+"(";var d=0;for(var e=0;e<b.length;e++){if(d>0)c+=", ";c+='"'+b[e]+'"';d++}c+=")";return c};RichMediaCreativeDisplayManager_69_11.prototype._splitArgs=function(a){var b=new Array;var c=unescape(a);var d=c.split("#mtf#");for(var e=0;e<d.length;e++)b[e]=d[e];return b};
RichMediaCreativeDisplayManager_69_11.prototype._parseCommandString=function(a){var b=new Object;b.command=unescape(a.split("=")[0]);b.argString=unescape(a.split("=")[1]);var c=b.argString.split("#mtf#");b.argArray=new Array;for(var d=0;d<c.length;d++)b.argArray[d]=c[d]=="null"?null:c[d];return b};
RichMediaCreativeDisplayManager_69_11.prototype._startDisplay=function(a,b){var c=this.toObject("DIV_"+a);var d=this.toObject("FLASH_"+a);if(b)this._adjustWindowElements(a,true);if(c)c.style.visibility="visible";if(d&&this.isFlashScriptingSupported())this.playFlash(a);var e=this.creative.renderingId;if(d&&this.debugEventsMode){if(!this.dartDebugEventBin.getShouldFlush(e)){this.setShouldFlush(e,true);this.dartDebugEventBin.flushMetCounters(e)}}else if(d&&!this.previewMode&&!this.dartEventBin.getShouldFlush(e))this.setShouldFlush(e,
true)};RichMediaCreativeDisplayManager_69_11.prototype.playFlash=function(a){var b=this.toObject("FLASH_"+a);var c=this.getAsset(a);var d=c.assetType;if(this.isInternetExplorer())b.Play();else if(d=="float"||d=="reminder"||d=="banner"||d=="expando")if(c.conduitInitialized){if(b.TCurrentFrame("/")<=0)b.Play()}else this.registerTimeoutHandler(100,"playFlash('"+a+"')",this)};
RichMediaCreativeDisplayManager_69_11.prototype._autoStopPlaying=function(a){var b=this.toObject("FLASH_"+a);if(b&&this.isFlashScriptingSupported())if(b.PercentLoaded()==100&&!b.IsPlaying())this.stopDisplay(a);else this.registerTimeoutHandler(300,"_autoStopPlaying('"+a+"')",this)};RichMediaCreativeDisplayManager_69_11.prototype._adjustWindowElements=function(a,b){this.pageElementsManager._adjustWindowElements(a,b)};RichMediaCreativeDisplayManager_69_11.prototype.triggerPoliteDownload=function(){for(var a in this.assets)if(!this.isPartOfArrayPrototype(a))this.finishPoliteDownload(a)};
RichMediaCreativeDisplayManager_69_11.prototype.finishPoliteDownload=function(a){var b=this.toObject("FLASH_"+a);if(this.isFlashObjectReady(this.creative.asVersion,b,a))this.setFlashVariable(this.creative.asVersion,b,"mtfContinue","1");else{var c="dartCreativeDisplayManagers['"+this.creativeIdentifier+"'].finishPoliteDownload('"+a+"');";window.setTimeout(c,100)}};RichMediaCreativeDisplayManager_69_11.prototype.triggerDispatchScriptLoaded=function(){for(var a in this.assets)if(!this.isPartOfArrayPrototype(a))this.finishDispatchScriptLoaded(a)};
RichMediaCreativeDisplayManager_69_11.prototype.finishDispatchScriptLoaded=function(a){var b=this.toObject("FLASH_"+a);try{if(b&&typeof b.PercentLoaded!="undefined"&&b.PercentLoaded()>0&&typeof b.TCurrentFrame!="undefined"&&b.TCurrentFrame("/")>=0)this.setFlashVariable(this.creative.asVersion,b,"globalTemplateScriptLoaded","1");else{var c="dartCreativeDisplayManagers['"+this.creativeIdentifier+"'].finishDispatchScriptLoaded('"+a+"');";window.setTimeout(c,100)}}catch(d){c="dartCreativeDisplayManagers['"+
this.creativeIdentifier+"'].finishDispatchScriptLoaded('"+a+"');";window.setTimeout(c,100)}};RichMediaCreativeDisplayManager_69_11.prototype.unloadPopup=function(){var a=this.renderingId;if(a){this.flushCounters(a);this.stopStandardTimers(a);this.logEvent("Stop",this.STANDARD_EVENT_INTERACTION_TIMER,a)}};RichMediaCreativeDisplayManager_69_11.prototype.forceAnimation=function(a){var b=this.toObject("FLASH_"+a);var c=this.toObject("DIV_"+a);if(c.style.visibility=="visible"){b.Zoom(50);b.Zoom(0)}};
RichMediaCreativeDisplayManager_69_11.prototype.isFlashScriptingSupported=function(){return this.isWindows()||(this.isMac()||this.isLinux())&&(this.isFirefox()||this.isSafari()||this.isChrome()||this.isOpera())};RichMediaCreativeDisplayManager_69_11.prototype.registerCreativeElement=function(a){this.rootElementArray[this.rootElementArray.length]=a};
RichMediaCreativeDisplayManager_69_11.prototype.removeChildNode=function(a,b){if(a.hasChildNodes()){var c=a.childNodes;for(var d=0;d<c.length;d++)this.removeChildNode(c[d],b)}else{var e=a.parentNode;e.removeChild(a);if(b!=e)this.removeChildNode(e,b)}};RichMediaCreativeDisplayManager_69_11.prototype.openPopupAsset=function(){if(this.overlay)this.overlay._openPopup()};RichMediaCreativeDisplayManager_69_11.prototype.closePopupAsset=function(){if(this.overlay)this.overlay._closePopup()};
RichMediaCreativeDisplayManager_69_11.prototype.registerOverlay=function(a){this.overlay=a};RichMediaCreativeDisplayManager_69_11.prototype.getAssetType=function(a){for(var b in this.creative.assets)if(this.creative.assets[b].variableName==a)return b;return null};RichMediaCreativeDisplayManager_69_11.prototype.setServedInIframe=function(a){this.servedInIframe=a};RichMediaCreativeDisplayManager_69_11.prototype.isServedInIframe=function(){return this.sourceIframe!=null};
RichMediaCreativeDisplayManager_69_11.prototype.setSourceIframe=function(a){this.sourceIframe=a};RichMediaCreativeDisplayManager_69_11.prototype.getSourceIframe=function(){return this.sourceIframe};
RichMediaCreativeDisplayManager_69_11.prototype.createHTML5AdIframe=function(a){var b="IFRAME_"+a.variableName;var c=document.createElement("IFRAME");c.id=b;c.src=a.url+"?liveEnvironment=true";c.scrolling="no";c.frameBorder="0";c.seamless=true;c.width=a.assetType=="Expanding"?a.expandedWidth:a.width;c.height=a.assetType=="Expanding"?a.expandedHeight:a.height;c.style.position="relative";c.style.top="0px";c.style.left="0px";c.style.width=(a.assetType=="Expanding"?a.expandedWidth:a.width)+"px";c.style.height=
(a.assetType=="Expanding"?a.expandedHeight:a.height)+"px";return c};RichMediaCreativeDisplayManager_69_11.prototype.invokeExternalJSFunction=function(a){if(this.creative.type!=this.CREATIVE_TYPE_EXPANDING)return;if(this.previewMode){var b=this.getEventBin();if(b!=null)b.logExternalJSFunctionCall(unescape(a),this.creative.renderingId)}else try{eval(unescape(a))}catch(c){}};RichMediaCreativeDisplayManager_69_11.prototype.setThrottlingWindow=function(a){var b=this.getEventBin();if(b!=null)if(this._isValidNumber(a))b.setMinimumFlushingDuration(parseFloat(a))};
RichMediaCreativeDisplayManager_69_11.prototype.logHTML5Impression=function(){var a=this.getEventBin();if(a){var b=this.getStandardEventId(this.STANDARD_EVENT_HTML5_CREATIVE_IMPRESSION);a.logMetEvent("Count",b,this.creative.renderingId,false,this.STANDARD_EVENT_HTML5_CREATIVE_IMPRESSION);a.flushMetCounters(this.creative.renderingId)}};RichMediaCreativeDisplayManager_69_11.prototype.attachMessageHandler=function(){self.addEventListener("message",this.bind(this,this.messageHandler),false)};
RichMediaCreativeDisplayManager_69_11.prototype.bind=function(a,b){var c=arguments.length>2?arguments.slice(2):[];return function(){return b.apply(a,arguments.slice?arguments.concat(c):arguments)}};RichMediaCreativeDisplayManager_69_11.prototype.messageHandler=function(a){var b=this.toObject(this.html5IframeId);if(b.contentWindow==a.source)this.messageCommandHandler(a)};
RichMediaCreativeDisplayManager_69_11.prototype.messageCommandHandler=function(a){var b=a.data;var c=this._parseCommandString(unescape(b));var d=this.createFunctionCall(c.command,c.argArray);try{eval('dartCreativeDisplayManagers["'+this.creativeIdentifier+'"].'+d)}catch(e){}};
RichMediaCreativeDisplayManager_69_11.prototype.invokeEnablerFunction=function(a,b,c){var d={};d.methodName=a;if(b&&b.join&&b.length>0)b=b.join("#mtf#");d.args=b?b:null;var e=this.getAsset(c);var f=document.getElementById("IFRAME_"+c).contentWindow;var g=this.getSiteProtocol(e.url)+"//"+this.getSiteHost(e.url);if(f)f.postMessage(escape(this.serializeCommand(d)),g)};RichMediaCreativeDisplayManager_69_11.prototype.serializeCommand=function(a){return escape(a.methodName)+"="+escape(a.args)};
RichMediaCreativeDisplayManager_69_11.prototype.setAdParameters=function(){var a=this.getHTML5Asset();if(a!=null)this.invokeEnablerFunction("setAdParameters",a.queryString,a.variableName)};
RichMediaCreativeDisplayManager_69_11.prototype.dispatchPageLoadToEnabler=function(){var a=this.getHTML5Asset();if(this.isPageLoaded)this.invokeEnablerFunction("dispatchPageLoaded","",a.variableName);else{var b="dartCreativeDisplayManagers['"+this.creativeIdentifier+"'].dispatchPageLoadToEnabler();";window.setTimeout(b,100)}};
function RichMediaEventBin_69_11(a,b,c){this.dartIntervalArray=b?new Array:new Array(10,20,50,120,240);this.dartEventBinCollection=new Array;this.dartRegistrationTime=null;this.dartMaxTimeMilliseconds=20*60*1000;this.dartCreativeIdentifier=a;this.timerAdjustments=new Array;this.lastEventFlushingTime=null;this.minimumFlushingDuration=5*1000;this.importantEventsArray=c;this.dynamicServeId=null}RichMediaEventBin_69_11.prototype=new RichMediaCore_69_11;
RichMediaEventBin_69_11.prototype.setTimerAdjustment=function(a,b,c){var d=new Object;d.eventId=a;d.startAdjustmentTime=parseInt(b);d.stopAdjustmentTime=parseInt(c);this.timerAdjustments[a]=d};
RichMediaEventBin_69_11.prototype.registerEventBinUrl=function(a,b){if(!this.dartEventBinCollection[a]){var c=new Array;c["counter"]=new Array;c["timer"]=new Array;c["duration"]=new Array;c["nonCumulativeCounters"]=new Array;c["flushUrl"]=b;c["shouldFlush"]=true;this.dartEventBinCollection[a]=c;this.dartRegistrationTime=new Date;this.setFlushInterval(a)}};RichMediaEventBin_69_11.prototype.setDynamicServeId=function(a){this.dynamicServeId=a};
RichMediaEventBin_69_11.prototype.logMetEvent=function(a,b,c,d){if(this.dartEventBinCollection[c]&&b&&!isNaN(b))switch(a){case "Count":{this.processCounter(b,c,d);break}case "Start":{this.processStart(b,c);break}case "Stop":{this.processStopTimer(b,c);break}default:break}};
RichMediaEventBin_69_11.prototype.processCounter=function(a,b,c){var d=this.getNonCumulativeCountersArray(b);var e=this.getCounterArray(b);c=c&&(c=="true"||c==true);if(!c){if(!d[a])e[a]=1;d[a]=true}else{if(!e[a])e[a]=0;e[a]=e[a]+1}};RichMediaEventBin_69_11.prototype.processStart=function(a,b){var c=this.getTimerArray(b);if(!c[a]){var d=new Date;var e=this.timerAdjustments[a];if(e){var f=d.getTime()+e.startAdjustmentTime;d.setTime(f)}c[a]=d;this.processCounter(a,b,false)}};
RichMediaEventBin_69_11.prototype.processStopTimer=function(a,b){var c=this.getTimerArray(b);var d=this.getDurationArray(b);if(c[a]){var e=c[a];var f=new Date;var g=f.getTime()-e.getTime();if(g<0||g>this.dartMaxTimeMilliseconds)g=0;d[a]=d[a]?d[a]+g:g;c[a]=false;return true}return false};RichMediaEventBin_69_11.prototype.shouldFlush=function(){var a=(new Date).getTime();return this.lastEventFlushingTime==null?true:a-this.lastEventFlushingTime>this.minimumFlushingDuration};
RichMediaEventBin_69_11.prototype.hasAnyImportantEventPending=function(a){var b=this.getCounterArray(a);for(var c in b)if(!this.isPartOfArrayPrototype(c)&&b[c]>0)for(var d=0;d<this.importantEventsArray.length;d++)if(c==this.importantEventsArray[d])return true;return false};
RichMediaEventBin_69_11.prototype.flushMetCounters=function(a){if(this.dartEventBinCollection[a]&&this.getShouldFlush(a)){var b="";var c=this.getCounterArray(a);var d=this.getDurationArray(a);var e=this.getTimerArray(a);var f=1;if((this.shouldFlush()||this.hasAnyImportantEventPending(a))&&this.isInAllowedTimeframe()){for(var g in c)if(!this.isPartOfArrayPrototype(g)){var h=this.processStopTimer(g,a);var i=c[g];if(!d[g])d[g]=0;var j=this.roundNumber(d[g]?parseFloat(String(d[g]/1000)):0);if(i>0||j>
0){b+="eid"+f+"="+g+";";b+="ecn"+f+"="+i+";";b+="etm"+f+"="+j+";"}c[g]=c[g]-i;d[g]=d[g]-j*1000;if(h)e[g]=new Date;f++}this.lastEventFlushingTime=(new Date).getTime();this.postData(b,a)}}};RichMediaEventBin_69_11.prototype.turnOffFlushing=function(a){this.flushMetCounters(a);this.setMetShouldFlush(false)};
RichMediaEventBin_69_11.prototype.postData=function(a,b){if(a.length){var c=new Date;var d=this.splitActivity(a);for(var e=0;e<d.length;e++){var f=document.createElement("img");var g=d[e];f.src=this.getFlushUrl(b)+this.getDynamicServeKeyvalue()+"&timestamp="+c.getTime()+";"+g}}};RichMediaEventBin_69_11.prototype.getDynamicServeKeyvalue=function(){return this.dynamicServeId?"rm_mid="+escape(this.dynamicServeId)+";":""};
RichMediaEventBin_69_11.prototype.splitActivity=function splitActivity(b){var c=new Array;var d="etm";var e=950;for(var f=0;b.length>0;b=b.substr(f)){var g=b;var h=g.substr(0,e);f=h.lastIndexOf(d)+d.length;h=g.substr(0,f);g=g.substr(f);f+=g.indexOf(";")+1;c[c.length]=b.substr(0,f)}return c};RichMediaEventBin_69_11.prototype.getCounterArray=function(a){var b=this.dartEventBinCollection[a];return b["counter"]};
RichMediaEventBin_69_11.prototype.getTimerArray=function(a){var b=this.dartEventBinCollection[a];return b["timer"]};RichMediaEventBin_69_11.prototype.getDurationArray=function(a){var b=this.dartEventBinCollection[a];return b["duration"]};RichMediaEventBin_69_11.prototype.getNonCumulativeCountersArray=function(a){var b=this.dartEventBinCollection[a];return b["nonCumulativeCounters"]};RichMediaEventBin_69_11.prototype.getFlushUrl=function(a){var b=this.dartEventBinCollection[a];return b["flushUrl"]};
RichMediaEventBin_69_11.prototype.getShouldFlush=function(a){var b=this.dartEventBinCollection[a];return b["shouldFlush"]};RichMediaEventBin_69_11.prototype.setMetShouldFlush=function(a,b){var c=this.dartEventBinCollection[a];if(c)c["shouldFlush"]=b};RichMediaEventBin_69_11.prototype.isInAllowedTimeframe=function(){var a=new Date;return!(a.getTime()-this.dartRegistrationTime.getTime()>this.dartMaxTimeMilliseconds)};
RichMediaEventBin_69_11.prototype.roundNumber=function(a,b){b=b?b:0;return Math.round(a*Math.pow(10,b))/Math.pow(10,b)};RichMediaEventBin_69_11.prototype.setFlushInterval=function(a){for(var b=0;b<this.dartIntervalArray.length;b++){var c=this.dartIntervalArray[b]*1000;this.registerTimeoutHandler(c,"flushMetCounters('"+a+"')",this)}};RichMediaEventBin_69_11.prototype.setMinimumFlushingDuration=function(a){this.minimumFlushingDuration=a*1000};
function MSNAdListener_69_11(a){this.asset=a;this.init()}MSNAdListener_69_11.prototype=new RichMediaCore_69_11;MSNAdListener_69_11.prototype.init=function(){var a=this.getAssetOffset();try{$WLXRmAd.init({width:parseFloat(this.asset.width),height:parseFloat(this.asset.height),offsetLeft:a.offsetLeft,offsetRight:a.offsetRight,offsetTop:a.assetTop,offsetBottom:a.offsetBottom})}catch(b){}};
MSNAdListener_69_11.prototype.getAssetOffset=function(){var a=new Object;a.offsetLeft=parseFloat(this.asset.offsetLeft)==0?0:parseFloat(this.asset.offsetLeft);a.offsetRight=parseFloat(this.asset.expandedWidth)==parseFloat(this.asset.offsetRight)?0:parseFloat(this.asset.expandedWidth)-parseFloat(this.asset.offsetRight);a.offsetTop=parseFloat(this.asset.offsetTop)==0?0:parseFloat(this.asset.offsetTop);a.offsetBottom=parseFloat(this.asset.expandedHeight)==parseFloat(this.asset.offsetBottom)?0:parseFloat(this.asset.expandedHeight)-
parseFloat(this.asset.offsetBottom);return a};MSNAdListener_69_11.prototype.expand=function(){try{$WLXRmAd.expand()}catch(a){}};MSNAdListener_69_11.prototype.collapse=function(){try{$WLXRmAd.collapse()}catch(a){}};function YahooAdListener_69_11(a){this.asset=a;this.init()}YahooAdListener_69_11.prototype=new RichMediaCore_69_11;YahooAdListener_69_11.prototype.init=function(){try{Y.SandBox.vendor.register(parseFloat(this.asset.width),parseFloat(this.asset.height))}catch(a){}};
YahooAdListener_69_11.prototype.getAssetOffset=function(){var a=new Object;a.offsetX=parseFloat(this.asset.offsetLeft)==0?parseFloat(this.asset.expandedWidth)-parseFloat(this.asset.width):-(parseFloat(this.asset.expandedWidth)-parseFloat(this.asset.width));a.offsetY=parseFloat(this.asset.offsetTop)==0?parseFloat(this.asset.expandedHeight)-parseFloat(this.asset.height):-(parseFloat(this.asset.expandedHeight)-parseFloat(this.asset.height));return a};
YahooAdListener_69_11.prototype.expand=function(){var a=this.getAssetOffset();try{Y.SandBox.vendor.expand(a.offsetX,a.offsetY)}catch(b){}};YahooAdListener_69_11.prototype.collapse=function(){try{Y.SandBox.vendor.collapse()}catch(a){}};
function DualAssetManager_69_11(a,b){this.creative=a;this.displayManager=b;this.assets=new Object;if(a.assets["floatAssets"])for(var c=0;c<this.creative.assets["floatAssets"].length;c++){var d=this.creative.assets["floatAssets"][c];this.assets[d.variableName]=d}else for(var e in a.assets)if(!this.isPartOfArrayPrototype(e))this.assets[a.assets[e].variableName]=a.assets[e]}DualAssetManager_69_11.prototype=new RichMediaCore_69_11;
DualAssetManager_69_11.prototype.getCompanionAssetName=function(a){for(var b in this.assets)if(!this.isPartOfArrayPrototype(b)&&b!=a)return b;return null};
DualAssetManager_69_11.prototype.getCompanionAssetForMultiFloating=function(a,b){for(var c in this.assets){switch(a.toLowerCase()){case "left":case "right":case "top":case "bottom":if(!this.isPartOfArrayPrototype(c)&&this.assets[c].alignment.toLowerCase()==a.toLowerCase())return c;continue}if(!this.isPartOfArrayPrototype(c)&&c!=a&&(!b&&this.displayManager.isAssetVisible(c)||b&&!this.displayManager.isAssetVisible(c)))return c}return null};
DualAssetManager_69_11.prototype.tellCompanionAssetStop=function(a){var b=this.getCompanionAssetName(a);if(b!=null)this.displayManager.tellAssetStop(b)};DualAssetManager_69_11.prototype.tellCompanionAssetStart=function(a){var b=this.getCompanionAssetName(a);if(b!=null)this.displayManager.tellAssetStart(b)};
DualAssetManager_69_11.prototype.tellCompanionAssetHide=function(a){var b=this.creative.type==this.CREATIVE_TYPE_MULTI_FLOATING?this.getCompanionAssetForMultiFloating(a,false):this.getCompanionAssetName(a);if(b!=null)this.displayManager.stopDisplay(b)};
DualAssetManager_69_11.prototype.tellCompanionAssetShow=function(a){var b=this.creative.type==this.CREATIVE_TYPE_MULTI_FLOATING?this.getCompanionAssetForMultiFloating(a,true):this.getCompanionAssetName(a);if(b!=null){var c=this.displayManager.getAsset(b);if(c!=null)if(c.isOverlay)this.displayManager.openPopupAsset(b);else if(c.assetType==this.ASSET_TYPE_FLOATING){if(this.isInternetExplorer()&&document.readyState!="complete"){this.registerPageLoadHandler("tellCompanionAssetShow('"+a+"')",this);return}var d=
this.displayManager.floatingManager.displayFloatingAsset(c);if(d)this.displayManager.floatingManager.logImpression(c)}else{var e=this.toObject("DIV_"+b);if(e&&e.style.visibility!="visible"){var f=this.toObject("FLASH_"+b);if(f&&this.displayManager.isFlashScriptingSupported()&&c.conduitInitialized){f.Rewind();f.StopPlay()}this.displayManager.scheduleDisplay(b,c.duration,true);if(c.isMainAsset){var g=this.displayManager.getRenderingId(b);this.displayManager.logEvent("Start","2",g)}}}}};
function PageElementsManager_69_11(a,b){this.creative=a;this.displayManager=b;this.dartEntityPropertiesArray=new Object;this.noAdjustElements=new _doNotAdjustElement;this.iframePlaceHolderDivIndex=0;this.hiddenIframes=new Array}PageElementsManager_69_11.prototype=new RichMediaCore_69_11;PageElementsManager_69_11.prototype.addEntityProperties=function(a,b,c,d,e,f,g){this.dartEntityPropertiesArray[a]=new _entityProperties(b,c,d,e,f,g)};
PageElementsManager_69_11.prototype.doNotAdjustIFrame=function(a,b){this.noAdjustElements.iFrames[this.noAdjustElements.iFrames.length]=b};PageElementsManager_69_11.prototype.doNotAdjustObject=function(a,b){this.noAdjustElements.objects[this.noAdjustElements.objects.length]=b};
PageElementsManager_69_11.prototype._adjustWindowElements=function(a,b){var c=this.dartEntityPropertiesArray[a];if(c){if(c.hideDropDowns)this._adjustElements(b,"select");if(c.hideScrollBars&&(this.isInternetExplorer()||this.isSafari()))this.adjustScrollbars(b);if(c.hideIFrames)this._adjustElements(b,"iframe");if(c.hideObjects){this._adjustElements(b,"object");this._adjustElements(b,"embed")}if(c.hideApplets)this._adjustElements(b,"applet");if(c.adjustZIndex)this._adjustZIndex(a,b)}};
PageElementsManager_69_11.prototype._adjustZIndex=function(a,b){try{this._adjustParentZIndex(a,b)}catch(c){}};
PageElementsManager_69_11.prototype._adjustParentZIndex=function(a,b){var c=this.toObject("DIV_"+a);var d=null;var e=this.displayManager.getAsset(a);if(c&&typeof e.assetType!="undefined"&&e.assetType==this.ASSET_TYPE_EXPANDING)d=c.parentNode.parentNode;else return;for(;d&&d.tagName!="BODY";){if(b){var f=this.getStyle(d);if(c.style.zIndex>f.zIndex&&(f.position=="relative"||f.position=="absolute")){d.style.originalZIndex=this.getStyle(d).zIndex;d.style.zIndex=c.style.zIndex}}else if(typeof d.style.originalZIndex!=
"undefined")d.style.zIndex=d.style.originalZIndex;d=d.parentNode}};PageElementsManager_69_11.prototype._adjustElements=function(a,b){var c=self.document.getElementsByTagName(b);b=b.toLowerCase();for(var d=0;d<c.length;d++){var e=true;if(b=="iframe")if(typeof c[d].MotifIFrameIDArray!="undefined")e=this._shouldAdjustIFrame(c[d].MotifIFrameIDArray);else e=!this.isHTML5ContainerIframe(c[d].id);else if(b=="object"||b=="embed")e=!this.isMotifObject(c[d].id);if(e)a?this.hideElement(c[d]):this.showElement(c[d])}};
PageElementsManager_69_11.prototype.hideElement=function(a){var b=a.getAttribute("hideCount");if(b==null||b==""){a.setAttribute("initialVisibility",a.style.visibility);a.setAttribute("hideCount",0);if(!a.getAttribute("hideCount")){a.initialVisibility=a.style.visibility;a.hideCount=0}}var c=parseInt(a.getAttribute("hideCount"));if(c==0)if(a.tagName.toLowerCase()=="iframe"&&this.isFirefox())this.hideFirefoxIFrame(a);else a.style.visibility="hidden";c++;a.setAttribute("hideCount",c);if(!a.getAttribute("hideCount"))a.hideCount=
c};PageElementsManager_69_11.prototype.showElement=function(a){if(a.getAttribute("hideCount")!=null){var b=parseInt(a.getAttribute("hideCount"));if(b!=0)b--;a.setAttribute("hideCount",b);if(!a.getAttribute("hideCount"))a.hideCount=b;if(b==0)if(a.tagName.toLowerCase()=="iframe"&&this.isFirefox())this.displayFirefoxIFrame(a);else a.style.visibility=a.getAttribute("initialVisibility")}};
PageElementsManager_69_11.prototype._shouldAdjustIFrame=function(a){var b=this.noAdjustElements.iFrames;for(var c=0;c<b.length;c++)for(var d=0;d<a.length;d++)if(b[c]==a[d])return false;return true};
PageElementsManager_69_11.prototype.isMotifObject=function(a){for(var b=0;b<dartMotifAds.length;b++){var c=dartMotifAds[b];if(c.assets["floatAssets"])for(b=0;b<c.assets["floatAssets"].length;b++){var d=c.assets["floatAssets"][b];if(a=="FLASH_"+d.variableName)return true}else for(var e in c.assets)if(a=="FLASH_"+c.assets[e].variableName)return true}return false};
PageElementsManager_69_11.prototype.isHTML5ContainerIframe=function(a){for(var b=0;b<dartMotifAds.length;b++){var c=dartMotifAds[b];for(var d in c.assets)if(a=="IFRAME_"+c.assets[d].variableName)return true}return false};function _entityProperties(a,b,c,d,e,f){this.hideDropDowns=a;this.hideIFrames=b;this.hideScrollBars=c;this.hideObjects=d;this.hideApplets=e;this.adjustZIndex=f}function _doNotAdjustElement(){this.iFrames=new Array;this.objects=new Array}
PageElementsManager_69_11.prototype.hideFirefoxIFrame=function(a){var b=null;var c=null;if(!a.hasAttribute("Motif_IFramePlaceHolderDivIndex")){b=document.createElement("DIV");b.id="MOTIF_IFRAMEPLACEHOLDER_"+this.iframePlaceHolderDivIndex;b.style.width="0px";b.style.height="0px";b.style.visibility="hidden";b.style.padding="0px";b.style.margin="0px";b.style.display="inline";a.parentNode.insertBefore(b,a);b.innerHTML='<img src="" width="0px" height="0px" padding="0px" margin="0px"></img>';a.setAttribute("Motif_IFramePlaceHolderDivIndex",
this.iframePlaceHolderDivIndex);c=new Object;this.hiddenIframes[this.iframePlaceHolderDivIndex]=c;this.iframePlaceHolderDivIndex++}else{var d=a.getAttribute("Motif_IFramePlaceHolderDivIndex");var e="MOTIF_IFRAMEPLACEHOLDER_"+d;b=document.getElementById(e);c=this.hiddenIframes[parseInt(d)]}c.width=a.width;c.height=a.height;b.style.width=c.width;b.style.height=c.height;b.firstChild.width=c.width;b.firstChild.height=c.height;a.style.visibility="hidden";a.width=0;a.height=0};
PageElementsManager_69_11.prototype.displayFirefoxIFrame=function(a){var b=a.getAttribute("Motif_IFramePlaceHolderDivIndex");var c="MOTIF_IFRAMEPLACEHOLDER_"+b;var d=document.getElementById(c);var e=this.hiddenIframes[parseInt(b)];if(d!=null){a.width=e.width;a.height=e.height;d.style.width="0px";d.style.height="0px";d.firstChild.width=0;d.firstChild.height=0}a.style.visibility=a.getAttribute("initialVisibility")};
PageElementsManager_69_11.prototype.adjustScrollbars=function(a){var b=self.document.documentElement;var c=document.compatMode&&document.compatMode=="CSS1Compat";c|=this.isSafari();if(a)if(c){b.style.originalOverflow=typeof b.currentStyle=="object"?b.currentStyle.overflow:b.style.overflow;b.style.overflow="hidden"}else self.document.body.scroll="no";else if(c){if(typeof b.style.originalOverflow!="undefined")b.style.overflow=b.style.originalOverflow}else self.document.body.scroll="yes"};
function FloatingManager_69_11(a,b){this.creative=a;this.displayManager=b;this.flashUtil=new FlashUtil_69_11(a);this.shouldLogImpression=true}FloatingManager_69_11.prototype=new RichMediaCore_69_11;FloatingManager_69_11.prototype.getPercentPosition=function(a,b,c){a=this.extractLength(a);b=parseInt(b);return(c-b)*a/100};FloatingManager_69_11.prototype.extractUnit=function(a){if(a.indexOf("%")>-1)return"%";else if(a.indexOf("pxc")>-1)return"pxc";else return"px"};
FloatingManager_69_11.prototype.extractLength=function(a){if(a.indexOf("%")>-1)return parseInt(a.substring(0,a.indexOf("%")));else if(a.indexOf("px")>-1)return parseInt(a.substring(0,a.indexOf("px")));else return parseInt(a)};
FloatingManager_69_11.prototype.getBodyLeft=function(){var a;var b;if(this.isInternetExplorer()){a=this.extractLength(document.body.currentStyle.left);b=document.body.currentStyle.position}else{var c=window.getComputedStyle(document.body,"");a=this.extractLength(c.getPropertyValue("left"));b=c.getPropertyValue("position")}if(b=="relative")a=(this.getWindowDimension().width-document.body.clientWidth)*0.5;return isNaN(parseInt(a))||a<1?0:a};
FloatingManager_69_11.prototype.adjustAdDiv=function(a,b){var c=this.extractLength(b.left);var d=this.extractLength(b.top);var e=this.getWindowDimension();var f=this.getScrollbarPosition();var g=this.extractUnit(b.left);var h=this.extractUnit(b.top);if(g=="%")c=this.getPercentPosition(b.left,b.width,e.width);else if(g=="pxc")c=c+e.width/2;if(h=="%")d=this.getPercentPosition(b.top,b.height,e.height);else if(h=="pxc")d=d+e.height/2;if((b.ignoreHorizontalScroll||b.ignoreVerticalScroll)&&this.checkBrowserForFixedSupport())a.style.position=
"fixed";else{if(b.ignoreHorizontalScroll)c=c+f.scrollLeft;if(b.ignoreVerticalScroll)d=d+f.scrollTop}if(typeof this.creative.isRelativeBody=="boolean"&&this.creative.isRelativeBody)c-=this.getBodyLeft();a.style.left=c+"px";a.style.top=d+"px"};
FloatingManager_69_11.prototype.checkBrowserForFixedSupport=function(){var a=document.createElement("div");a.style.cssText="position:absolute; top:0px; left:0px; margin:0px; padding:0px; border-width:0px; outline-width:0px;";document.body.appendChild(a);var b=document.createElement("div");b.style.cssText="position:fixed; top:10px;";a.appendChild(b);var c=0;if(typeof b.offsetTop=="number"&&b.offsetTop!=null&&b.offsetTop!="undefined")c=parseInt(b.offsetTop);a.removeChild(b);document.body.removeChild(a);
if(c==10)return true;return false};FloatingManager_69_11.prototype.adjustPosition=function(){for(var a in this.displayManager.assets)if(!this.isPartOfArrayPrototype(a)){var b=this.displayManager.getAsset(a);if(b.assetType==this.ASSET_TYPE_FLOATING||b.assetType==this.ASSET_TYPE_FLOATING){var c=this.toObject("DIV_"+a);if(c!=null)this.adjustAdDiv(c,b)}}};
FloatingManager_69_11.prototype.registerPercentPositioningHandler=function(){var a=false;var b=false;var c=false;for(var d in this.displayManager.assets)if(!this.isPartOfArrayPrototype(d)){var e=this.displayManager.getAsset(d);if(e.assetType==this.ASSET_TYPE_FLOATING||e.assetType==this.ASSET_TYPE_REMINDER){var f=this.extractUnit(e.top);var g=this.extractUnit(e.left);if(f=="%"||g=="%")a=true;if(e.ignoreVerticalScroll||e.ignoreHorizontalScroll)b=true;if(f=="pxc"||g=="pxc")c=true}}if(a||b||c)this.registerEventHandler("resize",
self,"adjustPosition()",this);if(b)this.registerEventHandler("scroll",self,"adjustPosition()",this)};
FloatingManager_69_11.prototype.createAdDiv=function(a){var b=document.createElement("DIV");b.id="DIV_"+a.variableName;b.style.position="absolute";b.style.zIndex=a.zIndex;b.style.visibility="hidden";var c=a.variableName;if(this.creative.shouldDisplayHTML5Asset){b.onmouseover=new Function("dartCreativeDisplayManagers['"+this.displayManager.creativeIdentifier+"'].onMouseOverHtml5('"+c+"');");b.ontouchstart=new Function("dartCreativeDisplayManagers['"+this.displayManager.creativeIdentifier+"'].onTouchHtml5('"+
c+"');");b.onmouseout=new Function("dartCreativeDisplayManagers['"+this.displayManager.creativeIdentifier+"'].onMouseOutHtml5('"+c+"');");b.ontouchend=new Function("dartCreativeDisplayManagers['"+this.displayManager.creativeIdentifier+"'].onTouchEndHtml5('"+c+"');")}else{b.onmouseover=new Function("dartCreativeDisplayManagers['"+this.displayManager.creativeIdentifier+"'].onMouseOver('"+c+"');");b.onmouseout=new Function("dartCreativeDisplayManagers['"+this.displayManager.creativeIdentifier+"'].onMouseOut('"+
c+"');");var d="FLASH_"+a.variableName;this.displayManager.doNotAdjustObject(a.variableName,d)}document.body.appendChild(b);if(this.displayManager.isServedInIframe())this.displayManager.registerCreativeElement(b);this.adjustAdDiv(b,a);this.displayManager.addEntityProperties(a.variableName,a.hideDropdowns,a.hideIframes,a.hideScrollbars,a.hideObjects,a.hideApplets,false);this.displayManager.registerUrl(this.creative.renderingId,this.creative.adserverUrl);return b};
FloatingManager_69_11.prototype.displayFloatingAsset=function(a){var b=false;try{var c=this.toObject("DIV_"+a.variableName);if(!c){c=this.createAdDiv(a);this.registerPercentPositioningHandler();b=true}if(c.style.visibility=="visible")return b;if(this.creative.shouldDisplayHTML5Asset)this.displayHTML5FloatingAsset(c,a);else this.displayFlashFloatingAsset(c,a)}catch(d){}return b};
FloatingManager_69_11.prototype.displayFlashFloatingAsset=function(a,b){var c=b.queryString+"&td="+escape(self.location.hostname);c+=this.usesSalignForExpanding(b.salign,b.wmode)?"&scaleMode=noScale":"";var d=this._convertDuration(b.duration)=="AUTO"?"false":"true";var e="FLASH_"+b.variableName;a.innerHTML=this.flashUtil.getObjectHtml("id",e,"name",e,"WIDTH",b.width,"HEIGHT",b.height,"movie",b.url,"quality","high","wmode",b.wmode,"salign",b.salign,"loop",d,"queryString",c);if(this.creative.type!=
this.CREATIVE_TYPE_INPAGE_WITH_FLOATING)RichMediaCore_69_11.prototype.trackCsiEvent("fb");a.style.visibility="visible";this.displayManager.fsHook(e);this.displayManager.scheduleDisplay(b.variableName,b.duration,true);this.displayManager.notifyPreviewHandler(b,"startDisplay");if(b.isPeelDown())this.displayManager.collapseAsset(b.variableName)};
FloatingManager_69_11.prototype.displayHTML5FloatingAsset=function(a,b){var c=this.displayManager.createHTML5AdIframe(b);this.displayManager.html5IframeId=c.id;this.displayManager.attachMessageHandler();a.appendChild(c);a.style.visibility="visible";this.displayManager.scheduleDisplay(b.variableName,b.duration,true);this.displayManager.notifyPreviewHandler(b,"startDisplay");this.displayManager.logHTML5Impression()};
FloatingManager_69_11.prototype.logImpression=function(a){if(a&&a.interstitialImage)this.trackUrl(a.interstitialImage,true,this.creative.previewMode)};FloatingManager_69_11.prototype.logThirdPartyImpression=function(){this.trackUrl(this.creative.thirdPartyImpUrl,true,this.creative.previewMode)};
FloatingManager_69_11.prototype.displayFloatingFlash=function(a){if(this.isInternetExplorer()&&document.readyState!="complete"){this.registerPageLoadHandler("displayFloatingFlash('"+a+"')",this);return}var b=this.creative.assets[this.ASSET_TYPE_FLOATING];if(this.creative.type==this.CREATIVE_TYPE_MULTI_FLOATING)b=this.displayManager.getAsset(a);this.displayFloatingAsset(b);if(this.shouldLogImpression){this.logImpression(b);this.logThirdPartyImpression();this.shouldLogImpression=false}};
FloatingManager_69_11.prototype.displayFloatingWithReminder=function(){var a=this.creative.assets[this.ASSET_TYPE_FLOATING];this.displayFloatingAsset(a);this.logImpression(a);var b=this.creative.assets[this.ASSET_TYPE_REMINDER];this.displayFloatingAsset(b)};
FloatingManager_69_11.prototype.getWindowDimension=function(){var a=new Object;if(document.documentElement&&document.compatMode=="CSS1Compat"){a.width=document.documentElement.clientWidth;a.height=document.documentElement.clientHeight}else if(document.body&&(document.body.clientWidth||document.body.clientHeight)&&!this.isSafari()){a.width=document.body.clientWidth;a.height=document.body.clientHeight}else if(typeof window.innerWidth=="number"){a.width=window.innerWidth;a.height=window.innerHeight}return a};
FloatingManager_69_11.prototype.getScrollbarPosition=function(){var a=new Object;a.scrollTop=0;a.scrollLeft=0;if(typeof window.pageYOffset=="number"){a.scrollTop=window.pageYOffset;a.scrollLeft=window.pageXOffset}else if(document.body&&(document.body.scrollLeft||document.body.scrollTop)){a.scrollTop=document.body.scrollTop;a.scrollLeft=document.body.scrollLeft}else if(document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)){a.scrollTop=document.documentElement.scrollTop;
a.scrollLeft=document.documentElement.scrollLeft}return a};function FlashUtil_69_11(a){this.creative=a}FlashUtil_69_11.prototype=new RichMediaCore_69_11;FlashUtil_69_11.prototype.getObjectHtml=function(){var a=this.getArgs(arguments);return this.generateObj(a.objAttrs,a.params,a.embedAttrs)};
FlashUtil_69_11.prototype.getArgs=function(a){var b=new Object;b.embedAttrs=new Object;b.params=new Object;b.objAttrs=new Object;var c="";var d=false;for(var e=0;e<a.length;e=e+2){var f=a[e].toLowerCase();switch(f){case "codebase":case "pluginspage":case "type":case "classid":case "minversion":break;case "src":case "movie":b.params["movie"]=b.embedAttrs["src"]=a[e+1];break;case "querystring":c=a[e+1]=a[e+1]+"&br="+escape(this.getBrowser())+"&os="+escape(this.getOS());break;case "width":case "height":case "align":case "vspace":case "hspace":case "class":case "title":case "accesskey":case "name":case "id":case "tabindex":case "alt":case "onmouseover":case "onmouseout":b.embedAttrs[a[e]]=
b.objAttrs[a[e]]=a[e+1];break;case "swliveconnect":b.embedAttrs[a[e]]=a[e+1];break;case "wmode":d=this.isFlashFullScreenSupported(a[e+1]);b.embedAttrs[a[e]]=b.params[a[e]]=a[e+1];break;default:b.embedAttrs[a[e]]=b.params[a[e]]=a[e+1]}}c+="&isFlashFullScreenEnabled="+d;b.params["FlashVars"]=b.embedAttrs["FlashVars"]=c;b.objAttrs["classid"]="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";b.embedAttrs["type"]="application/x-shockwave-flash";b.params["allowScriptAccess"]="always";b.embedAttrs["allowScriptAccess"]=
"always";if(d){b.params["allowFullScreen"]="true";b.embedAttrs["allowFullScreen"]="true"}if(this.isFirefox())b.embedAttrs["style"]="outline:none";return b};
FlashUtil_69_11.prototype.generateObj=function(a,b,c){var d="";if(this.isInternetExplorer()){d+="<object ";for(var e in a)if(!this.isPartOfArrayPrototype(e))d+=e+'="'+a[e]+'" ';d+=">";for(e in b)if(!this.isPartOfArrayPrototype(e))d+='<param name="'+e+'" value="'+b[e]+'" /> '}d+="<embed ";for(e in c)if(!this.isPartOfArrayPrototype(e))d+=e+'="'+c[e]+'" ';d+=" />";if(this.isInternetExplorer())d+="</object>";return d};
FlashUtil_69_11.prototype.getBrowser=function(){if(this.isInternetExplorer())return"ie";else if(this.isFirefox())return"ff";else if(this.isSafari())return"sf";else if(this.isChrome())return"cr";else if(this.isOpera())return"op";else return"NOT_SUPPORTED"};FlashUtil_69_11.prototype.getOS=function(){if(this.isWindows())return"win";if(this.isMac())return"mac";if(this.isLinux())return"linux";if(this.isAndroid())return"android";else return"NOT_SUPPORTED"};
FlashUtil_69_11.prototype.isFlashFullScreenSupported=function(a){var b=this.getPluginInfo();var c=this.creative.requiredPlayerVersion;if(c>5&&this.creative.fullScreenEnabled)if(b>=9.115||b>=9.28&&a=="window")return true;return false};function IFrameCreativeRenderer_69_11(){}IFrameCreativeRenderer_69_11.prototype=new RichMediaCore_69_11;
IFrameCreativeRenderer_69_11.prototype.removeCreative=function(a,b){var c=dartCreativeDisplayManagers[a];if(typeof c=="undefined"||c==null)return;if(c.creative.type==this.CREATIVE_TYPE_EXPANDING&&!b)this.revertExpandingAdChanges(a,c);c.removeArrayElement(dartCallbackObjects,c);c.deleteCreative(b);dartCreativeDisplayManagers[a]=null};
IFrameCreativeRenderer_69_11.prototype.revertExpandingAdChanges=function(a,b){var c=self.document.getElementsByTagName("iframe");for(var d=0;d<c.length;d++)if(typeof c[d].MotifIFrameIDArray!="undefined")for(var e=0;e<c[d].MotifIFrameIDArray.length;e++)if(c[d].MotifIFrameIDArray[e]==a){var f=b.creative.assets[this.ASSET_TYPE_EXPANDING];c[d].width=c[d].originalWidth?c[d].originalWidth:f.width;c[d].height=c[d].originalHeight?c[d].originalHeight:f.height;c[d].style.width=c[d].originalWidth?c[d].originalWidth:
f.width+"px";c[d].style.height=c[d].originalHeight?c[d].originalHeight:f.height+"px";break}};
IFrameCreativeRenderer_69_11.prototype.displayCreative=function(a,b){var c=false;if(typeof a.MsnDapIF!="undefined"&&a.MsnDapIF)c=true;var d=new RichMediaCreativeDisplayManager_69_11(a,b);if(a.type==this.CREATIVE_TYPE_FLOATING){dartCreativeDisplayManagers[a.creativeIdentifier]=d;var e=new FloatingManager_69_11(a,d);var f=a.assets[this.ASSET_TYPE_FLOATING];if(this._isValidStartTime(f.startTime))d.registerTimeoutHandler(eval(f.startTime)*1000,"displayFloatingFlash()",e)}else if(a.type==this.CREATIVE_TYPE_EXPANDING){dartCreativeDisplayManagers[a.creativeIdentifier]=
d;var g=new ExpandingManager_69_11(a,d);d.setExpandingManager(g);var h=new ExpandingIFrameRenderer_69_11(d,g,a);h.processExpandingBreakout(a,b,c,g)}else if(a.type==this.CREATIVE_TYPE_INPAGE_WITH_FLOATING){dartCreativeDisplayManagers[a.creativeIdentifier]=d;var i=new InpageIFrameRenderer_69_11(a,d);f=a.assets[this.ASSET_TYPE_FLOATING];e=new FloatingManager_69_11(a,d);d.setFloatingManager(e);i.processInpageBreakout(a,b,c,e);if(this._isValidStartTime(f.startTime))d.registerTimeoutHandler(eval(f.startTime)*
1000,"displayFloatingFlash()",e)}else if(a.type==this.CREATIVE_TYPE_MULTI_FLOATING){dartCreativeDisplayManagers[a.creativeIdentifier]=d;e=new FloatingManager_69_11(a,d);d.setFloatingManager(e);for(var j=0;j<a.assets["floatAssets"].length;j++){f=a.assets["floatAssets"][j];if(this._isValidStartTime(f.startTime))d.registerTimeoutHandler(eval(f.startTime)*1000,"displayFloatingFlash('"+f.variableName+"')",e)}}};
IFrameCreativeRenderer_69_11.prototype.processCreative=function(a){var b=self.richMediaIframeBreakoutCreatives[a].creative;this.displayCreative(b,b.sourceIframe)};IFrameCreativeRenderer_69_11.prototype.showCreative=function(a){if(this.isInternetExplorer())this.registerPageLoadHandler("processCreative('"+a+"')",this);else this.processCreative(a)};
IFrameCreativeRenderer_69_11.prototype.loadPlCrJs=function(a,b,c){var d=c.document.createElement("SCRIPT");RichMediaCore_69_11.prototype.trackCsiEvent("pb");d.src=a;var e=c.document.getElementsByTagName("head");if(this.isInternetExplorer()&&e.length>0)e[0].appendChild(d);else if(b.parentNode.parentNode)b.parentNode.parentNode.appendChild(d);else b.parentNode.insertBefore(d,b)};
IFrameCreativeRenderer_69_11.prototype.isGlobalTemplateCompatible=function(a){var b="floatingIframe";if(a.globalTemplateVersion!="69_11")return false;switch(a.type){case this.CREATIVE_TYPE_FLOATING:return b=="floatingIframe";case this.CREATIVE_TYPE_EXPANDING:return b=="expandingIframe";case this.CREATIVE_TYPE_INPAGE_WITH_FLOATING:return b=="inpageFloatingIframe";case this.CREATIVE_TYPE_MULTI_FLOATING:return b=="floatingIframe";default:return false}};
IFrameCreativeRenderer_69_11.prototype.loadPlcrScripts=function(){for(var a=0;a<self.richMediaIframeBreakoutCreatives.length;a++){var b=self.richMediaIframeBreakoutCreatives[a];RichMediaCore_69_11.prototype.setCsiEventsRecordedDuringBreakout(b);if(this.isGlobalTemplateCompatible(b)){var c=b.sourceIframe;var d=b.plcrScript;this.loadPlCrJs(d,c,self)}}};(new IFrameCreativeRenderer_69_11).loadPlcrScripts();RichMediaCore_69_11.prototype.trackCsiEvent("ge");